################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: Europe/Amsterdam
  unit_system: metric
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
conversation:
frontend:
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover

  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
     - sensor.pihole_ads_blocked_today
     - sensor.pihole_ads_percentage_blocked_today
     - sensor.pihole_dns_queries_today
     - sensor.since_last_boot
     - sensor.since_last_boot_templated
     - sensor.ha_uptime
     - sensor.time
sun:
python_script:
logger: !include logger.yaml
recorder:
  purge_keep_days: 2
discovery:
  ignore:
    - sonos
    - samsung_tv
    - google_cast

ios:
  push:
    categories:
      - name: Weather
        identifier: 'WEATHERFORECAST'
        actions:
          - identifier: 'SEND_1D_WEATHERFORECAST'
            title: 'Weersverwachting overdag' # Needs to be short!
            activationMode: 'background' # foreground or background. The mode in which to run the app when the action is performed.
            authenticationRequired: no # A Boolean value indicating whether the user must unlock the device before the action is performed.
            destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
            behavior: 'default' # default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          - identifier: 'SEND_1N_WEATHERFORECAST'
            title: 'Weersverwachting vannacht' # Needs to be short!
            activationMode: 'background' # foreground or background. The mode in which to run the app when the action is performed.
            authenticationRequired: no # A Boolean value indicating whether the user must unlock the device before the action is performed.
            destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
            behavior: 'default' # default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.

################################################
## Components (Non-Includes)
################################################

ffmpeg:

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_cerificate_file
  ssl_key: !secret ssl_key_file
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.ups_status_date
    domains:
      - sun

mqtt:
  discovery: true 
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

influxdb:
  host: !secret influxDB_host

tts:
  - platform: google
    language: 'nl'

hue:
  bridges:
    - host: !secret hue_bridge_ip
    - allow_hue_groups: false

ifttt:
  key: !secret ifttt_key

################################################
## Component Includes (Single File)
################################################

################################################
## Component Includes (Named)
################################################

# alexa:
#   intents: !include_dir_named alexa

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list device_tracker
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
zone: !include_dir_merge_list zone
switch: !include_dir_merge_list switch

################################################
## Component Includes (Merge Named)
################################################

#group: !include_dir_merge_named group
#input_boolean: !include_dir_merge_named input_boolean
#input_slider: !include_dir_merge_named input_slider
#panel_iframe: !include_dir_merge_named panel_iframe
script: !include_dir_merge_named script
