################################################################
## Configuration
################################################################

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  time_zone: Europe/Amsterdam
  unit_system: metric
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
conversation:
frontend:
history:
sun:
python_script:
discovery:
  ignore:
    - sonos
    - samsung_tv
    - google_cast
#ios:

################################################
## Components (Non-Includes)
################################################

ffmpeg:

http:
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_cerificate_file
  ssl_key: !secret ssl_key_file
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.date
      - sensor.ups_status_date
    domains:
      - sun

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

#influxdb:
#  host: !secret influxDB_host

tts:
  - platform: google
    language: 'nl'

hue:
  bridges:
    - host: !secret hue_bridge_ip

################################################
## Component Includes (Single File)
################################################

################################################
## Component Includes (Named)
################################################

# alexa:
#   intents: !include_dir_named alexa

################################################
## Component Includes (Merge List)
################################################

automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list device_tracker
light: !include_dir_merge_list light
media_player: !include_dir_merge_list media_player
notify: !include_dir_merge_list notify
zone: !include_dir_merge_list zone
switch: !include_dir_merge_list switch

################################################
## Component Includes (Merge Named)
################################################

#group: !include_dir_merge_named group
#input_boolean: !include_dir_merge_named input_boolean
#input_slider: !include_dir_merge_named input_slider
#panel_iframe: !include_dir_merge_named panel_iframe
#script: !include_dir_merge_named script
