################################################################
## Z-Wave / Device Config
################################################################

################################################
## Scullery multisensor
################################################

binary_sensor.bijkeuken_sensor_sensor_2_0:
  ignored: true

sensor.bijkeuken_sensor_alarm_level_2_1:
  ignored: true

sensor.bijkeuken_sensor_alarm_type_2_0:
  ignored: true

sensor.bijkeuken_sensor_sourcenodeid_2_2:
  ignored: true

sensor.bijkeuken_sensor_ultraviolet_2_27:
  ignored: true

################################################
## Hallway multisensor
################################################

binary_sensor.hal_sensor_sensor_3_0:
  ignored: true

sensor.hal_sensor_alarm_level_3_1:
  ignored: true

sensor.hal_sensor_alarm_type_3_0:
  ignored: true

sensor.hal_sensor_sourcenodeid_3_2:
  ignored: true

sensor.hal_sensor_ultraviolet_3_27:
  ignored: true
