################################################################
## Z-Wave / Device Config
################################################################

################################################
## Bathroom multisensor
################################################

binary_sensor.bathroom_sensor_sensor:
  ignored: true

sensor.bathroom_sensor_alarm_level:
  ignored: true

sensor.bathroom_sensor_alarm_type:
  ignored: true

sensor.bathroom_sensor_sourcenodeid:
  ignored: true

sensor.bathroom_sensor_ultraviolet:
  ignored: true

################################################
## Hallway multisensor
################################################

binary_sensor.hal_sensor_sensor:
  ignored: true

sensor.hal_sensor_alarm_level:
  ignored: true

sensor.hal_sensor_alarm_type:
  ignored: true

sensor.hal_sensor_sourcenodeid:
  ignored: true

sensor.hal_sensor_ultraviolet:
  ignored: true
