################################################################
## Z-Wave / Device Config
################################################################

################################################
## Scullery multisensor
################################################

!secret binary_sensor_scullery:
  ignored: true

!secret sensor_scullery_alarm_level:
  ignored: true

!secret sensor_scullery_alarm_type:
  ignored: true

!secret sensor_scullery_source_nodeid:
  ignored: true

!secret sensor_scullery_ultraviolet:
  ignored: true

################################################
## Hallway multisensor
################################################

!secret binary_sensor_hallway:
  ignored: true

!secret sensor_hallway_alarm_level:
  ignored: true

!secret sensor_hallway_alarm_type:
  ignored: true

!secret sensor_hallway_source_nodeid:
  ignored: true

!secret sensor_hallway_ultraviolet:
  ignored: true

################################################
## Dishwasher switch with energy measurements
################################################

!secret sensor_dishwasher_exporting:
  ignored: true
  hidden: true

!secret sensor_dishwasher_param10:
  ignored: true
  hidden: true

!secret sensor_dishwasher_param18:
  ignored: true
  hidden: true

!secret sensor_dishwasher_param2:
  ignored: true
  hidden: true

!secret sensor_dishwasher_param22:
  ignored: true
  hidden: true

!secret sensor_dishwasher_powermanagement:
  ignored: true
  hidden: true

!secret sensor_dishwasher_kwh_previous_reading:
  ignored: true
  hidden: true

!secret sensor_dishwasher_current_previous_reading:
  ignored: true
  hidden: true

!secret sensor_dishwasher_power_previous_reading:
  ignored: true
  hidden: true

!secret sensor_dishwasher_source_nodeId:
  ignored: true
  hidden: true

!secret sensor_dishwasher_mains_voltage_previous_reading:
  ignored: true
  hidden: true
