################################################################
## Z-Wave / Device Config
################################################################

################################################
## Scullery multisensor
################################################

binary_sensor.bijkeuken_sensor_sensor:
  ignored: true

sensor.bijkeuken_sensor_alarm_level:
  ignored: true

sensor.bijkeuken_sensor_alarm_type:
  ignored: true

sensor.bijkeuken_sensor_sourcenodeid:
  ignored: true

sensor.bijkeuken_sensor_ultraviolet:
  ignored: true

################################################
## Hallway multisensor
################################################

binary_sensor.hal_sensor_sensor:
  ignored: true

sensor.hal_sensor_alarm_level:
  ignored: true

sensor.hal_sensor_alarm_type:
  ignored: true

sensor.hal_sensor_sourcenodeid:
  ignored: true

sensor.hal_sensor_ultraviolet:
  ignored: true
