################################################################
## Light
################################################################

################################################
## Philips Hue
################################################
- platform: hue
  host: !secret hue_bridge_ip
  allow_unreachable: true
  allow_hue_groups: false
