################################################################
## Light
################################################################

################################################
## Philips Hue
################################################
- platform: hue
  host: !secret hue_bridge_ip
  allow_unreachable: true
  allow_hue_groups: false

- platform: mqtt_json
  name: "MultiSensor1-LED"
  state_topic: "ahpaleis/multisensor1"
  command_topic: "ahpaleis/multisensor1/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
