automation:
  - alias: Arm the house for the start of the day. at 6am if it is a weekday
    initial_state: 'on'
    trigger:
      - platform: time
        at: '06:00:00'
    condition:
      - condition: state
        entity_id: group.family
        state: home
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.night_mode
      - service: homeassistant.turn_on
        entity_id: input_boolean.first_movement_of_the_day
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamerled
          color_name: green
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.overloop_led
          color_name: green
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.bijkeuken_led
          color_name: green
          brightness: 1
          transition: 1
