################################################################
## Packages / Bathroom
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    packages.bathroom: &customize
      package: 'bathroom'

    packages.bathroom_exposed: &customize_exposed
      <<: *customize

    packages.bathroom_contained: &customize_contained
      <<: *customize

    group.bathroom:
      <<: *customize_contained
      friendly_name: "Badkamer"

    ################################################
    ## Bathroom Ventilator
    ################################################
    switch.bathroom_vent_switch:
      <<: *customize_contained
      friendly_name: "Ventilator"
      icon: mdi:fan
      initial_state: 'off'

    sensor.bathroom_vent_previous_reading:
      hidden: true

    sensor.bathroom_vent_exporting:
      hidden: true

    sensor.bathroom_vent_interval:
      hidden: true

    sensor.bathroom_vent_power_management:
      hidden: true

    sensor.bathroom_vent_sourcenodeid:
      hidden: true

    sensor.bathroom_vent_alarm_level:
      hidden: true

    sensor.bathroom_vent_alarm_type:
      hidden: true

    binary_sensor.bathroom_vent_power_usage_templated:
      hidden: true

    ################################################
    ## Bathroom Multisensor
    ################################################
    sensor.bathroom_motion_detector:
      <<: *customize_contained
      friendly_name: "Aanwezigheid"
      device_class: motion
      icon: mdi:walk

    sensor.bathroom_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.bathroom_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.bathroom_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.bathroom_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

    sensor.mold_indicator:
      <<: *customize_contained
      friendly_name: "Schimmelontwikkeling"
      icon: mdi:water-percent

################################################
## Group
################################################
group:
  bathroom:
    control: hidden
    entities:
      - sensor.bathroom_motion_detector
      - sensor.bathroom_sensor_temperature
      - sensor.bathroom_sensor_relative_humidity
      - sensor.mold_indicator
      - sensor.bathroom_sensor_luminance
      - switch.bathroom_vent_switch
      - sensor.bathroom_vent_power_usage_templated

################################################
## Sensor
################################################
sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.bathroom_sensor_temperature
    indoor_humidity_sensor: sensor.bathroom_sensor_relative_humidity
    outdoor_temp_sensor: sensor.pws_temp_c
    calibration_factor: 1.26
  - platform: template
    sensors:
      bathroom_motion_detector:
        value_template: >-
            {%- if is_state("sensor.bathroom_sensor_burglar", "8") %}
                Ja
            {% elif is_state("sensor.bathroom_sensor_burglar", "0") %}
                Nee
            {%- endif %}

binary_sensor:
  - platform: template
    sensors:
      bathroom_vent_power_usage_templated:
        value_template: "{{ states('sensor.bathroom_vent_power') | int < 5 }}"
        entity_id: sensor.bathroom_vent_power

################################################
## Automation
################################################
automation:
  ################################################
  ## When motion detected, switch off bathroom vent
  ################################################
  - alias: bathroom_vent_off_when_human_present
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.bathroom_sensor_burglar
        to: '8'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.bathroom_vent_switch

  ################################################
  ## When no more motion detected, switch on bathroom vent if needed
  ################################################
  - alias: bathroom_vent_on_when_no_motion_and_too_humid
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.bathroom_sensor_burglar
        to: '0'
        for:
          minutes: 5
    action:
      - service: homeassistant.turn_on
        entity_id: script.timed_ventilator

  ################################################
  ## When no motion, and mold indicator >70, switch fan on
  ################################################
  - alias: bathroom_vent_on_when_high_mold
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_indicator
        value_template: '{{ state.attributes.value}}'
        above: '70'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.bathroom_motion_detector
          state: 'nee'
    action:
      - service: homeassistant.turn_on
        entity_id: script.timed_ventilator

  ################################################
  ## Periodically check if fan needs to be switched on
  ##
  ## This is needed because the humidity updates
  ## do not happen regularly, with no motion detected
  ## after a while the fan will have finished a cycle
  ## and may then sit idle for a long while. This is
  ## time in which mold could develop.
  ################################################
  - alias: periodically_check_if_fan_needs_to_be_on
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: time
        minutes: '/5'
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.bathroom_motion_detector
          state: 'nee'
        - condition: numeric_state
          entity_id: sensor.mold_indicator
          value_template: '{{ state.attributes.value}}'
          above: '70'
        - condition: state
          entity_id: switch.bathroom_vent_switch
          state: 'off'
          for:
            minutes: 5
    action:
      - service: homeassistant.turn_on
        entity_id: script.timed_ventilator
      - service: notify.pushover
        data_template:
          title: "Ventilator aan"
          message: "de 5 minuten check is geweest en de ventilator gaat nu aan"
