################################################################
## Packages / Bathroom
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    packages.bathroom: &customize
      package: 'bathroom'

    packages.bathroom_exposed: &customize_exposed
      <<: *customize

    packages.bathroom_contained: &customize_contained
      <<: *customize

    group.bathroom:
      <<: *customize_contained
      friendly_name: "Badkamer"

    ################################################
    ## Bathroom Ventilator
    ################################################
    switch.bathroom_vent_switch:
      <<: *customize_contained
      friendly_name: "Ventilator"
      icon: mdi:toys
      persistent: true

    sensor.bathroom_vent_previous_reading_4:
      hidden: true

    sensor.bathroom_vent_exporting:
      hidden: true

    sensor.bathroom_vent_interval_2:
      hidden: true

    sensor.bathroom_vent_interval_3:
      hidden: true

    sensor.bathroom_vent_interval:
      hidden: true

    sensor.bathroom_vent_interval_4:
      hidden: true

    sensor.bathroom_vent_previous_reading_2:
      hidden: true

    sensor.bathroom_vent_power_management:
      hidden: true

    sensor.bathroom_vent_previous_reading:
      hidden: true

    sensor.bathroom_vent_previous_reading_3:
      hidden: true

    sensor.bathroom_vent_sourcenodeid:
      hidden: true

    sensor.bathroom_vent_alarm_level:
      hidden: true

    sensor.bathroom_vent_alarm_type:
      hidden: true

    binary_sensor.bathroom_vent_power_usage_templated:
      hidden: true

    ################################################
    ## Bathroom Multisensor
    ################################################
    sensor.bathroom_motion_detector:
      <<: *customize_contained
      friendly_name: "Aanwezigheid"
      icon: mdi:walk

    sensor.bathroom_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.bathroom_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.bathroom_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.bathroom_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

################################################
## Group
################################################
group:
  bathroom:
    control: hidden
    entities:
      - sensor.bathroom_motion_detector
      - sensor.bathroom_sensor_temperature
      - sensor.bathroom_sensor_relative_humidity
      - sensor.bathroom_sensor_luminance
      - switch.bathroom_vent_switch
      - sensor.bathroom_vent_power_usage_templated

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      bathroom_motion_detector:
        value_template: >-
            {%- if is_state("binary_sensor.bathroom_sensor_sensor", "on") %}
                Ja
            {% elif is_state("binary_sensor.bathroom_sensor_sensor", "off") %}
                Nee
            {%- endif %}

binary_sensor:
  - platform: template
    sensors:
      bathroom_vent_power_usage_templated:
        value_template: "{{ states('sensor.bathroom_vent_power_6_8') | int < 5 }}"
        entity_id: sensor.bathroom_vent_power_6_8
