################################################################
## Sensor / Time Based Brightness
## Original author: Dale Higgs (@Dale3H)
################################################################

# @todo Automation for setting light brightness when global changes
# @todo Add individual light brightnesses
# @todo Is there a way to implement machine learning for individual lights?

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'brightness'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

    automation.update_global_brightness:
      <<: *customize
      friendly_name: "Update Global Brightness"

    ################################################
    ## Input Slider
    ################################################

    input_number.global_brightness:
      <<: *customize
      friendly_name: "Global Brightness"

    input_number.nightlight_brightness:
      <<: *customize
      friendly_name: "Nightlight Brightness"

    input_number.global_color_temp:
      <<: *customize
      friendly_name: "Global Color Temperature"

    ################################################
    ## Sensor
    ################################################

    sensor.global_brightness:
      <<: *customize
      friendly_name: "Global Brightness"
      hidden: true

    sensor.global_color_temp:
      <<: *customize
      friendly_name: "Global Color Temperature"
      hidden: true

################################################
## Automation
################################################

automation:
  - alias: update_global_color_temp
    trigger:
      - platform: time
        minutes: '/1'
        seconds: '00'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.global_color_temp
          value: >-
            {% set color_temp = {
              0: 500,
              1: 500,
              2: 500,
              3: 500,
              4: 500,
              5: 500,
              6: 500,
              7: 350,
              8: 275,
              9: 200,
              10: 154,
              11: 154,
              12: 154,
              13: 154,
              14: 154,
              15: 154,
              16: 154,
              17: 154,
              18: 154,
              19: 154,
              20: 250,
              21: 350,
              22: 450,
              23: 500,
            } %}
            {{ color_temp[now().hour]|default(255) }}

  - alias: update_global_brightness
    trigger:
      - platform: time
        hours: '/1'
        minutes: '00'
        seconds: '00'
    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.global_brightness
          value: >-
            {% set brightness = {
              0: 1,
              1: 1,
              2: 1,
              3: 1,
              4: 1,
              5: 1,
              6: 1,
              7: 25,
              8: 150,
              9: 150,
              10: 255,
              11: 255,
              12: 255,
              13: 255,
              14: 255,
              15: 255,
              16: 255,
              17: 255,
              18: 255,
              19: 255,
              20: 192,
              21: 128,
              22: 64,
              23: 20,
            } %}
            {{ brightness[now().hour]|default(255) }}

################################################
## Input Slider
################################################

input_number:
  global_brightness:
    initial: 255
    min: 0
    max: 255
    step: 1

  nightlight_brightness:
    initial: 32
    min: 0
    max: 255
    step: 16

  global_color_temp:
    initial: 275
    min: 154
    max: 500
    step: 1

################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      global_brightness:
        value_template: >-
          {% set time_now = states('sensor.time').replace(':', '.')|float %}
          {% if time_now < 7 %}
            64
          {% elif time_now < 8 %}
            128
          {% elif time_now < 9 %}
            192
          {% elif time_now < 20 %}
            255
          {% elif time_now < 21 %}
            192
          {% elif time_now < 22 %}
            128
          {% else %}
            64
          {% endif %}

      global_color_temp:
        value_template: >-
          {% set time_now = states('sensor.time').replace(':', '.')|float %}
          {% if time_now < 7 %}
            500
          {% elif time_now < 8 %}
            350
          {% elif time_now < 9 %}
            225
          {% elif time_now < 10 %}
            154
          {% elif time_now < 20 %}
            225
          {% elif time_now < 21 %}
            350
          {% elif time_now < 22 %}
            450
          {% elif time_now < 23 %}
            500
          {% else %}
            275
          {% endif %}
