################################################################
## Packages / Energy usage and measurements.
################################################################


################################################
## Customize
################################################

homeassistant:
  customize:
    packages.energy: &customize
      package: 'energy'

    packages.energy_exposed: &customize_exposed
      <<: *customize

    packages.energy_contained: &customize_contained
      <<: *customize

    automation.notify_meter_readings_at_midnight:
      <<: *customize
      friendly_name: "Meterstanden notificatie"
      icon: mdi:comment-alert-outline

    group.total_energy_consumption:
      <<: *customize_contained
      friendly_name: "Energie verbruik"
      icon: mdi:gauge

    sensor.gas_consumption:
      <<: *customize_contained
      friendly_name: "Meterstand Gas"

    sensor.hourly_gas_consumption:
      <<: *customize_contained
      friendly_name: "Gasverbruik per uur"

    sensor.power_consumption:
      <<: *customize_contained
      friendly_name: "Electriciteit verbruik"

    sensor.power_consumption_low:
      <<: *customize_contained
      friendly_name: "Meterstand daltarief"
      icon: mdi:speedometer

    sensor.power_consumption_normal:
      <<: *customize_contained
      friendly_name: "Meterstand normaal tarief"
      icon: mdi:speedometer

    sensor.energytariff_nl:
      <<: *customize_contained
      friendly_name: "Actief tarief"
      icon: mdi:currency-eur

    sensor.power_tariff:
      hidden: true

    sensor.woonkamer_dimmer_energy:
      <<: *customize_contained
      friendly_name: "Zithoek dimmer"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_energy:
      <<: *customize_contained
      friendly_name: "Bijkeuken lamp"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_energy_2:
      <<: *customize_contained
      friendly_name: "Buitenlamp achterdeur"
      icon: mdi:lightbulb

    sensor.power_production:
      hidden: true

    sensor.power_production_low:
      hidden: true

    sensor.power_production_normal:
      hidden: true

    group.current_power_consumption:
      <<: *customize_contained
      friendly_name: "Huidig verbruik"
      icon: mdi:flash

    sensor.woonkamer_dimmer_power_2:
      <<: *customize_contained
      friendly_name: "Zithoek dimmer"
      icon: mdi:lightbulb

    sensor.woonkamer_dimmer_power:
      hidden: true

    sensor.achterdeur_schakelaars_power:
      <<: *customize_contained
      friendly_name: "Bijkeuken lamp"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_power_2:
      <<: *customize_contained
      friendly_name: "Buitenlamp achterdeur"
      icon: mdi:lightbulb

    sensor.vaatwasser_power:    # Dishwasher: Watts
      <<: *customize_contained
      friendly_name: "Vaatwasser"
      icon: mdi:power-plug

    sensor.vaatwasser_voltage: # Dishwasher: Volts
      <<: *customize_contained
      friendly_name: "Vaatwasser spanning"
      icon: mdi:power-plug

    sensor.vaatwasser_current: # Dishwasher: Amps
      <<: *customize_contained
      friendly_name: "Vaatwasser stroom"
      icon: mdi:power-plug

    sensor.vaatwasser_energy: # Dishwasher: Current power usage
      <<: *customize_contained
      friendly_name: "Vaatwasser"
      icon: mdi:power-plug

    sensor.stats_mean:
      <<: *customize_contained
      friendly_name: "Gemiddeld stroomverbruik"
      icon: mdi:flash

################################################
## Automation
################################################

automation:

  ################################################
  ## Notification at midnight with readings from the smart meter
  ################################################
  - alias: notify_meter_readings_at_midnight
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:00'
    action:
      service: notify.pushover
      data_template:
        title: "Meterstanden"
        message: "Hoog: {{ states.sensor.power_consumption_normal.state }}, Laag: {{ states.sensor.power_consumption_low.state }}, Gas: {{ states.sensor.gas_consumption.state }}. Min-temp: {{ states.sensor.dark_sky_daily_low_temperature.state }}, Max-temp: {{ states.sensor.dark_sky_daily_high_temperature.state }}"


################################################
## Group
################################################
group:
  total_energy_consumption:
    control: hidden
    entities:
      - sensor.gas_consumption
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.stats_mean
      - sensor.energytariff_nl
      - sensor.vaatwasser_energy   # Dishwasher kWh
      - sensor.woonkamer_dimmer_energy
      - sensor.achterdeur_schakelaars_energy       # Scullery light
      - sensor.achterdeur_schakelaars_energy_2     # Backdoor outside light

  current_power_consumption:
    control: hidden
    entities:
      - sensor.hourly_gas_consumption
      - sensor.power_consumption
      - sensor.vaatwasser_power    # Dishwasher: Watts
      - sensor.vaatwasser_current # Dishwasher: Amps
      - sensor.vaatwasser_voltage # Dishwasher: Volts
      - sensor.woonkamer_dimmer_power_2
      - sensor.achterdeur_schakelaars_power        # Scullery light
      - sensor.achterdeur_schakelaars_power_2      # Backdoor outside light

################################################
## Sensor
################################################

sensor:
  - platform: dsmr
    port: /dev/slimmemeter
    dsmr_version: 4
  - platform: template
    sensors:
      energytariff_nl:
        friendly_name: 'Tarief'
        value_template: >-
            {%- if is_state("sensor.power_tariff", "low") %}
                Dal (€ 0,1669/kWh)
            {% elif is_state("sensor.power_tariff", "normal") %}
                Normaal (€ 0,1781/kWh)
            {%- endif %}
      low_tariff_meter_value_at_midnight:
        value_template: >
          {% if now().hour == 0 and now().minute == 0 %}
            {{ states.sensor.power_consumption_low.attributes.value | float }}
