################################################################
## Packages / Energy usage and measurements
################################################################
## 30-may-17 - Added Smart Meter info

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.energy: &customize
      package: 'energy'

################################################
## Group
################################################
group:
  ups:
    control: hidden
    entities:
      - sensor.gas_consumption
      - sensor.hourly_gas_consumption
      - sensor.power_consumption
      - sensor.power_consumption_low
      - sensor.power_consumption_normal
      - sensor.energytariff_nl
################################################
## Sensor
################################################

sensor:
  - platform: dsmr
    port: /dev/slimmemeter
    dsmr_version: 4
  - platform: template
    sensors:
      energytariff_nl:
        friendly_name: 'Tarief'
        value_template: >-
            {%- if is_state("sensor.power_tariff", "low") %}
                Dal (€ 0,1669/kWh)
            {% elif is_state("sensor.power_tariff", "normal") %}
                Normaal (€ 0,1781/kWh)
            {%- endif %}
