################################################################
## Packages / Hallway.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.hallway: &customize
      package: 'hallway'

    packages.hallway_exposed: &customize_exposed
      <<: *customize

    packages.hallway_contained: &customize_contained
      <<: *customize

    group.hallway:
      <<: *customize_contained
      friendly_name: "Hal"

    ### Hallway Multisensor
    sensor.hallway_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.hal_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.hal_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.hal_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.hal_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

################################################
## Group
################################################
group:
  hallway:
    control: hidden
    entities:
      - sensor.hallway_motion_detector
      - sensor.hal_sensor_temperature
      - sensor.hal_sensor_relative_humidity
      - sensor.hal_sensor_luminance
      - light.hal


################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      hallway_motion_detector:
        value_template: >-
            {%- if is_state("sensor.hal_sensor_burglar", "8") %}
                Beweging
            {% elif is_state("sensor.hal_sensor_burglar", "0") %}
                Geen beweging
            {%- endif %}
