################################################################
## Packages / Hallway.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.hallway: &customize
      package: 'hallway'

    packages.hallway_exposed: &customize_exposed
      <<: *customize

    packages.hallway_contained: &customize_contained
      <<: *customize

    group.hallway:
      <<: *customize_contained
      friendly_name: "Hal"

    ### Hallway Multisensor
    sensor.hallway_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.hal_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.hal_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.hal_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.hal_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

################################################
## Group
################################################
group:
  hallway:
    control: hidden
    entities:
      - sensor.hallway_motion_detector
      - sensor.hal_sensor_temperature
      - sensor.hal_sensor_relative_humidity
      - sensor.hal_sensor_luminance
      - light.hal


################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      hallway_motion_detector:
        value_template: >-
            {%- if is_state("sensor.hal_sensor_burglar", "8") %}
                Beweging
            {% elif is_state("sensor.hal_sensor_burglar", "0") %}
                Geen beweging
            {%- endif %}

################################################
## Automation
################################################
automation:
  ################################################
  ## Increase brightness in hallway when motion detected and not in night mode
  ################################################
  - alias: when_motion_detected_brighten_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        from: '0'
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: python_script.dimmer
        data_template:
          entity_id: light.hal
          action: dim_up
          level: 150

  ################################################
  ## Decrease brightness in hallway when motion no longer detected and not in night mode
  ################################################
  - alias: when_no_more_motion_dim_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        from: '8'
        to: '0'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: python_script.dimmer
        data_template:
          entity_id: light.hal
          action: dim_down
          level: 150

  ################################################
  ## Light dimmed on in hallway when motion detected and in night mode
  ################################################
  - alias: hallway_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        from: '0'
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: python_script.dimmer
        data_template:
          entity_id: light.hal
          action: dim_up
          level: 25

  ################################################
  ## Hhallway light off when motion no longer detected and in night mode
  ################################################
  - alias: hallway_light_off_when_no_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        from: '8'
        to: '0'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: python_script.dimmer
        data_template:
          entity_id: light.hal
          action: dim_down
          level: 25
