################################################################
## Packages / Hallway
################################################################


################################################
## Customize
################################################
## Note: The zwave sensor stuff is already customized in the zwave package

homeassistant:
  customize:
    packages.hallway: &customize
      package: 'energy'

    packages.hallway_exposed: &customize_exposed
      <<: *customize

    packages.hallway_contained: &customize_contained
      <<: *customize


################################################
## Group
################################################
group:
  hallway:
    control: hidden
    entities:
      - sensor.hal_sensor_burglar_3_10
      - sensor.hal_sensor_temperature_3_1
      - sensor.hal_sensor_relative_humidity_3_5
      - ensor.hal_sensor_luminance_3_3
