################################################################
## Packages / Hallway.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.hallway: &customize
      package: 'hallway'

    packages.hallway_exposed: &customize_exposed
      <<: *customize

    packages.hallway_contained: &customize_contained
      <<: *customize

    group.hallway:
      <<: *customize_contained
      friendly_name: "Hal"

    ### Hallway Multisensor
    sensor.hallway_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.hal_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.hal_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.hal_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.hal_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

################################################
## Group
################################################
group:
  hallway:
    control: hidden
    entities:
      - sensor.hallway_motion_detector
      - sensor.hal_sensor_temperature
      - sensor.hal_sensor_relative_humidity
      - sensor.hal_sensor_luminance
      - light.hal_2


################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      hallway_motion_detector:
        value_template: >-
            {%- if is_state("sensor.hal_sensor_burglar", "8") %}
                Beweging
            {% elif is_state("sensor.hal_sensor_burglar", "0") %}
                Geen beweging
            {%- endif %}

################################################
## Automation
## Note: turning on lights when the sun sets, is programmed in
## a separate file: sunrise_sunset.yaml
################################################
automation:
  - alias: test_switch_automation
    initial_state: 'on'
    hide_entity: false
    trigger:
      - platform: state
        entity_id: input_boolean.test_switch
        to: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hal_2
          #rgb_color: 248,255,248
          color_name: white
          #brightness: 250
          transition: 1

  ################################################
  ## Turn light full on during day when lightlevel<20
  ##
  ## When sun is below horizon, light level is obviously<20, but
  ## this is bright, daylight light, so we only want that when it is actually
  ## day outside as well :-)
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Above horizon
  ##  Light level: <20
  ################################################
  - alias: motion_light_on_during_the_day_when_too_dark
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - condition: numeric_state
          entity_id: 'sensor.hal_sensor_luminance'
          below: '20'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hal_2
          color_name: white
          brightness: 250
          transition: 1

  ################################################
  ## Turn light off when no more motion detected during the day
  ##
  ## Trigger: motion to no-motion
  ## Conditions:
  ##  Sun: Above horizon
  ##  Light level: <20
  ################################################
  - alias: motion_light_off_during_the_day_when_no_motion
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '0'
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.hal_2
          transition: 3

  ################################################
  ## Increase brightness in hallway when motion detected and not in night mode
  ##
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Below horizon
  ##  Night Mode: OFF
  ################################################
  - alias: when_motion_detected_brighten_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hal_2
          brightness: 150
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          brightness: 150
          transition: 1
      #- service: python_script.dimmer
      #  data_template:
      #    entity_id: light.hal_2
      #    action: dim_up
      #    level: 150
      #- service: python_script.dimmer
      #  data_template:
      #    entity_id: light.verloop
      #    action: dim_up
      #    level: 150

  ################################################
  ## Decrease brightness in hallway when motion no longer detected and not in night mode
  ################################################
  - alias: when_no_more_motion_dim_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '0'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hal_2
          brightness: 50
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          brightness: 50
          transition: 1
      #- service: python_script.dimmer
      #  data_template:
      #    entity_id: light.hal_2
      #    action: dim_down
      #    level: 150
      #- service: python_script.dimmer
      #  data_template:
      #    entity_id: light.verloop
      #    action: dim_down
      #    level: 150

  ################################################
  ## Light dimmed on in hallway when motion detected and in night mode
  ################################################
  - alias: hallway_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.hal_2
          color_name: red
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          color_name: red
          brightness: 1
          transition: 1


  ################################################
  ## Hallway light off when motion no longer detected and in night mode
  ################################################
  - alias: hallway_light_off_when_no_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '0'
        for:
          minutes: 2
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.hal_2
          transition: 1
      - service: light.turn_off
        data_template:
          entity_id: light.overloop
          transition: 1
