################################################################
## Packages / Hallway.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.hallway: &customize
      package: 'hallway'

    packages.hallway_exposed: &customize_exposed
      <<: *customize

    packages.hallway_contained: &customize_contained
      <<: *customize

    group.hallway:
      <<: *customize_contained
      friendly_name: "Hal"

    ### Hallway Multisensor
    sensor.hallway_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.hal_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.hal_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.hal_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.hal_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

################################################
## Group
################################################
group:
  hallway:
    control: hidden
    entities:
      - sensor.hallway_motion_detector
      - sensor.hal_sensor_temperature
      - sensor.hal_sensor_relative_humidity
      - sensor.hal_sensor_luminance
      - light.hal_2


################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      hallway_motion_detector:
        value_template: >-
            {%- if is_state("sensor.hal_sensor_burglar", "8") %}
                Beweging
            {% elif is_state("sensor.hal_sensor_burglar", "0") %}
                Geen beweging
            {%- endif %}

################################################
## Automation
################################################
automation:
  ################################################
  ## Turn light full on during day when lightlevel<20
  ##
  ## When sun is below horizon, light level is obviously<20, but
  ## this is bright, daylight light, so we only want that when it is actually
  ## day outside as well :-)
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Above horizon
  ##  Light level: <20
  ################################################
  - alias: 'Hallway light dim-up when motion and sun above horizon but dark'
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - condition: numeric_state
          entity_id: 'sensor.hal_sensor_luminance'
          below: '20'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hal_2
          color_temp: 154
          brightness: 250
          transition: 1
      - delay: '00:03:00'
      - service: light.turn_off
        data:
          entity_id: light.hal_2
          transition: 1

  ################################################
  ## Increase brightness in hallway when motion detected and not in night mode
  ##
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Below horizon
  ##  Night Mode: OFF
  ################################################
  - alias: 'Hallway light dim-up when motion and sun below horizon'
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hal_2
          color_temp: 300
          brightness: 150
          transition: 1
      - delay: '00:03:00'
      - service: light.turn_on
        data:
          entity_id: light.hal_2
          color_temp: 300
          brightness: 50
          transition: 1

  ################################################
  ## Light dimmed on in hallway when motion detected and in night mode
  ################################################
  - alias: hallway_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.hal_sensor_burglar
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hal_2
          color_name: red
          brightness: 1
          transition: 1
      - delay: '00:05:00'
      - service: light.turn_off
        data:
          entity_id: light.hal_2
          transition: 1
