###############################################################################
#   @author         :   Arno Jansen (original author: Mahasri Kalavala)
#   @package        :   Holidays
#   @description    :   Gets holiday info
###############################################################################
## Modified for my own fun stuff!

homeassistant:
  customize:

    sensor.holiday:
      hidden: true
      icon: mdi:beach
      friendly_name: NL Feestdag
    sensor.flag:
      hidden: true
      icon: mdi:flag
      friendly_name: Vlag Dag

###############################################################################
# Sensor updates once every 4 hours (14400 seconds) & runs 6 times in 24 hours
#
# First it checks for holiday in static section, if that doesn't exist,
# it checks in the dynamic section. If neither exists, the value will be empty
###############################################################################
sensor:
  - platform: rest
    resource: https://raw.githubusercontent.com/aetjansen/HomeAssistant-Config/master/json_data/holidays.json
    name: Feestdag
    scan_interval: 14400
    value_template: >
      {% set today = now().day  ~ '-' ~ now().month  %}
      {% set holiday =  value_json.MAJOR_NL.static[ today ] %}
      {% if holiday | trim == "" %}
        {% set today = now().day  ~ '-' ~ now().month ~ '-' ~ now().year %}
        {% set holiday =  value_json.MAJOR_NL.dynamic[ today ] %}
      {% endif %}
      {{ holiday }}

  - platform: rest
    resource: http://www.webcal.fi/cal.php?id=482&format=json&start_year=current_year&end_year=2023&tz=Europe%2FAmsterdam
    name: Flag
    scan_interval: 14400
    value_template: >-
      {% set is_flag_day = False %}
      {%- for day_val in value_json -%}
        {% set now_string = now().strftime('%Y-%m-%d') %}
        {%- if day_val.date == now_string and day_val.flag_day == 1-%}
          {% set is_flag_day = day_val.name + ' (' + day_val.age + '). ' + day_val.description + ' ' + day_val.url %}
        {%- endif -%}
      {% endfor %}
      {{is_flag_day}}

###############################################################################
# Automation that notifies of a Holiday "state" change
###############################################################################
automation:
  - alias: Notify Holiday State Change
    hide_entity: false
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.holiday
    condition:
      - condition: template
        value_template: "{{ states('sensor.holiday') != 'unknown' }}"
      - condition: template
        value_template: "{{ states.sensor.holiday.state | trim != '' }}"
    action:
      - service: notify.pushover
        data_template:
          title: "{{ states.sensor.holiday.state }}"
          message: "Vandaag is {{ states.sensor.holiday.state }}."

  - alias: Notify Flag Day
    hide_entity: false
    initial_state: true
    trigger:
      - platform: state
        entity_id:
          - sensor.flag
    condition:
      - condition: template
        value_template: "{{ states('sensor.flag') != 'unknown' }}"
      - condition: template
        value_template: "{{ states('sensor.flag') != 'False' }}"
      - condition: template
        value_template: "{{ states.sensor.flag.state | trim != '' }}"
    action:
      - service: notify.pushover
        data_template:
          title: "De vlag mag uit!"
          message: "Voor: {{ states.sensor.flag.state }}."
