################################################
## Packages / Kitchen
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.kitchen: &customize
      package: 'kitchen'

    packages.kitchen_exposed: &customize_exposed
      <<: *customize

    packages.kitchen_contained: &customize_contained
      <<: *customize

    switch.vaatwasser_switch_6_0:
      <<: *customize_contained
      friendly_name: "Vaatwassser"
      icon: mdi:powerplug
      hidden: true

    sensor.vaatwasser_previous_reading_6_21:
      hidden: true

    sensor.vaatwasser_exporting_6_32:
      hidden: true

    sensor.vaatwasser_interval_6_10:
      hidden: true

    sensor.vaatwasser_interval_6_18:
      hidden: true

    sensor.vaatwasser_interval_6_2:
      hidden: true

    sensor.vaatwasser_interval_6_22:
      hidden: true

    sensor.vaatwasser_previous_reading_6_9:
      hidden: true

    sensor.vaatwasser_power_management_6_11:
      hidden: true

    sensor.vaatwasser_previous_reading_6_1:
      hidden: true

    sensor.vaatwasser_previous_reading_6_17:
      hidden: true

    sensor.vaatwasser_sourcenodeid_6_2:
      hidden: true

    sensor.vaatwasser_alarm_level_6_1:
      hidden: true

    sensor.vaatwasser_alarm_type_6_0:
      hidden: true

################################################
## Automation
################################################
automation:

  ################################################
  ## Notification when the dishwasher is ready.
  ## It's power usage drops to 0W when ready,
  ## so if it is a 0W for 2 minutes, send a notification
  ## (power consumption can briefly drop to (near) 0W
  ## during a washing cycle for a few seconds, hence
  ## the 2 minute wait time)
  ################################################
  - alias: "Notify when dishwasher is done"
    trigger:
      - platform: state
        entity_id: binary_sensor.vaatwasser_power_usage_templated
        from: 'off'
        to: 'on'
        for:
          minutes: 2
          seconds: 0
    action:
      service: notify.pushover
      data_template:
        title: "Vaatwasser klaar"
        message: "De vaatwasser is klaar met het wasprogramma!"



################################################
## Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      vaatwasser_power_usage_templated:
        value_template: "{{ states('sensor.vaatwasser_power_6_8') | int < 5 }}"
        entity_id: sensor.vaatwasser_power_6_8
