################################################
## Packages / Kitchen
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.kitchen: &customize
      package: 'kitchen'

    packages.kitchen_exposed: &customize_exposed
      <<: *customize

    packages.kitchen_contained: &customize_contained
      <<: *customize

    switch.vaatwasser_switch_6_0:
      <<: *customize_contained
      friendly_name: "Vaatwassser"
      icon: mdi:powerplug
      hidden: true
