################################################
## Packages / Kitchen
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.kitchen: &customize
      package: 'kitchen'

    packages.kitchen_exposed: &customize_exposed
      <<: *customize

    packages.kitchen_contained: &customize_contained
      <<: *customize

    group.kitchen:
      <<: *customize_contained
      friendly_name: "Keuken"

################################################
## Automation
################################################

################################################
## Sensor
################################################

################################################
## Group
################################################
