################################################
## Packages / Landing
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.landing: &customize
      package: 'landing'

    packages.landing_exposed: &customize_exposed
      <<: *customize

    packages.landing_contained: &customize_contained
      <<: *customize

    group.landing:
      <<: *customize_contained
      friendly_name: "Overloop"

################################################
## Group
################################################
group:
  landing:
    control: hidden
    entities:
      - sensor.overloop_temperatuur
      - sensor.overloop_luchtvochtigheid
      - sensor.overloop_licht
      - sensor.overloop_beweging
      - light.overloop_led
      - light.overloop

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop luchtvochtigheid"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop licht"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "Lux"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop beweging"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop temperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop gevoelstemperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'

################################################
## Light
################################################
light:
  - platform: mqtt_json
    name: "Overloop Led"
    state_topic: "ahpaleis/landing"
    command_topic: "ahpaleis/landing/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

################################################
## Automation
################################################
automation:
  ################################################
  ## Turn light full on during day when lightlevel<20
  ##
  ## When sun is below horizon, light level is obviously<20, but
  ## this is bright, daylight light, so we only want that when it is actually
  ## day outside as well :-)
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Above horizon
  ##  Light level: <20
  ################################################
  - alias: motion_light_on_during_the_day_when_too_dark
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.overloop_beweging
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - condition: numeric_state
          entity_id: 'sensor.hal_sensor_luminance'
          below: '20'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          color_temp: 154
          brightness: 250
          transition: 1
      - delay: '00:05:00'
      - service: light.turn_off
        data_template:
          entity_id: light.overloop
          transition: 1

  ################################################
  ## Increase brightness in hallway when motion detected and not in night mode
  ##
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Below horizon
  ##  Night Mode: OFF
  ################################################
  - alias: when_motion_detected_brighten_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.overloop_beweging
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          color_temp: 300
          brightness: 150
          transition: 1
      - delay: '00:01:00'
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          color_temp: 300
          brightness: 50
          transition: 1
      #- service: python_script.dimmer
      #  data_template:
      #    entity_id: light.hal_2
      #    action: dim_up
      #    level: 150
      #- service: python_script.dimmer
      #  data_template:
      #    entity_id: light.verloop
      #    action: dim_up
      #    level: 150


  ################################################
  ## Light dimmed on in hallway when motion detected and in night mode
  ################################################
  - alias: landing_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.overloop_beweging
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          color_name: red
          brightness: 1
          transition: 1
      - delay: "00:01:00"
      - service: light.turn_off
        data_template:
          entity_id: light.overloop
          transition: 1
