################################################
## Packages / Landing
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.landing: &customize
      package: 'landing'

    packages.landing_exposed: &customize_exposed
      <<: *customize

    packages.landing_contained: &customize_contained
      <<: *customize

    group.landing:
      <<: *customize_contained
      friendly_name: "Overloop"

################################################
## Group
################################################
group:
  landing:
    control: hidden
    entities:
      - sensor.overloop_temperatuur
      - sensor.overloop_luchtvochtigheid
      - sensor.overloop_licht
      - sensor.overloop_beweging
      - light.overloop_led
      - light.overloop

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop luchtvochtigheid"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop licht"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop beweging"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop temperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: "Overloop gevoelstemperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'

################################################
## Light 
################################################
light:
  - platform: mqtt_json
    name: "Overloop Led"
    state_topic: "ahpaleis/landing"
    command_topic: "ahpaleis/landing/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
