################################################
## Packages / Landing
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.landing: &customize
      package: 'landing'

    packages.landing_exposed: &customize_exposed
      <<: *customize

    packages.landing_contained: &customize_contained
      <<: *customize

    group.landing:
      <<: *customize_contained
      friendly_name: "Overloop"

################################################
## Group
################################################
group:
  landing:
    control: hidden
    entities:
      - sensor.landing_temperature
      - sensor.landing_humidity
      - sensor.landing_light_level
      - sensor.landing_motion
      - light.landing_led
      - light.landing

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: landing humidity
    friendly_name: "Overloop luchtvochtigheid"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: landing light level
    friendly_name: "Overloop licht"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "Lux"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: landing motion
    friendly_name: "Overloop beweging"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/landing"
    name: landing temperature
    friendly_name: "Overloop temperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

################################################
## Light
################################################
light:
  - platform: mqtt_json
    name: landing led
    friendly_name: "Overloop Led"
    state_topic: "ahpaleis/landing"
    command_topic: "ahpaleis/landing/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

################################################
## Automation
################################################
automation:
  ################################################
  ## Turn light full on during day when lightlevel<20
  ##
  ## When sun is below horizon, light level is obviously<20, but
  ## this is bright, daylight light, so we only want that when it is actually
  ## day outside as well :-)
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Above horizon
  ##  Light level: <20
  ################################################
  - alias: motion_light_on_during_the_day_when_too_dark
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.landing_motion
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - condition: numeric_state
          entity_id: 'sensor.landing_light_level'
          below: '20'
    action:
      - service: light.turn_on
        data:
          entity_id: light.landing
          color_temp: 154
          brightness: 250
          transition: 1

  - alias: motion_light_off_during_the_day_when_too_dark
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.landing_motion
        to: 'standby'
        for:
          minutes: 3
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'above_horizon'
        - condition: numeric_state
          entity_id: 'sensor.landing_light_level'
          below: '20'
    action:
      - service: light.turn_off
        data:
          entity_id: light.landing
          transition: 1

  ################################################
  ## Increase brightness in hallway when motion detected and not in night mode
  ##
  ## Trigger: motion
  ## Conditions:
  ##  Sun: Below horizon
  ##  Night Mode: OFF
  ################################################
  - alias: when_motion_detected_brighten_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.landing_motion
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.landing
          color_temp: 300
          brightness: 150
          transition: 1

  - alias: when_no_more_motion_detected_dim_light
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.landing_motion
        to: 'standby'
        for:
          minutes: 3
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.landing
          color_temp: 300
          brightness: 50
          transition: 1


  ################################################
  ## Light dimmed on in hallway when motion detected and in night mode
  ################################################
  - alias: landing_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.landing_motion
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.landing
          color_name: red
          brightness: 1
          transition: 1

  - alias: landing_light_off_when_no_more_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.landing_motion
        to: 'standby'
        for:
          minutes: 1
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.landing
          transition: 1
