################################################################
## Packages / livingroom.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.livingroom: &customize
      package: 'livingroom'

    packages.livingroom_exposed: &customize_exposed
      <<: *customize

    packages.livingroom_contained: &customize_contained
      <<: *customize

    group.livingroom:
      <<: *customize_contained
      friendly_name: "Woonkamer"

    light.woonkamer_dimmer_step_size_5_6_2:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6:
      hidden: true

    light.woonkamer_dimmer_level_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0:
      <<: *customize_contained
      friendly_name: "Zithoek"

    sensor.woonkamer_dimmer_alarm_level:
      hidden: true

    sensor.woonkamer_dimmer_alarm_level_2:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type_2:
      hidden: true

    sensor.woonkamer_dimmer_exporting:
      hidden: true

    sensor.woonkamer_dimmer_heat:
      hidden: true

    sensor.woonkamer_dimmer_power_management:
      hidden: true

    sensor.woonkamer_dimmer_sourcenodeid:
      hidden: true

    sensor.woonkamer_dimmer_system:
      hidden: true

    sensor.woonkamer_dimmer_unknown_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0_3:
      hidden: true

    light.woonkamer_dimmer_level_5_0_4:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_3:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_4:
      hidden: true

    light.plafondlamp_speelkamer:
      <<: *customize_contained
      friendly_name: "Speelhoek"

    light.iris:
      <<: *customize_contained
      friendly_name: "Iris"

    light.leeslamp:
      <<: *customize_contained
      friendly_name: "Leeslamp"

    ### LIvingroom Multisensor
    sensor.livingroom_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk

    sensor.livingroom_motion:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.livingroom_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.livingroom_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.livingroom_lightlevel:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

    sensor.livingroom_heatindex:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:thermometer
      hidden: true


################################################
## Automation
################################################

automation:

  ################################################
  ## Notification at midnight with readings from the smart meter
  ################################################
  - alias: Notify_double_click_fibaro_dimmer
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          scene_id: 14
          object_id: woonkamer_dimmer_5
    action:
      service: notify.ios_iphone_van_arno
      data_template:
        title: "Double Click detected!"
        message: "Als dit werkt betekent het dat je kunt automatiseren als reactie op een dubbel klik van de fibaro dimmer 2!"


################################################
## Group
################################################
group:
  livingroom:
    control: hidden
    entities:
      - sensor.livingroom_motion_detector
      - sensor.livingroom_temperature
      - sensor.livingroom_humidity
      - sensor.livingroom_lightlevel
      - light.multisensor1led
      - light.woonkamer_dimmer_level_5_0
      - light.plafondlamp_speelkamer
      - light.iris
      - light.leeslamp

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_lightlevel"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "Lux"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_temperature"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_heatindex"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: template
    name: "livingroom_motion_detector"
    value_template: >-
            {%- if is_state("livingroom_motion", "motion detected") %}
                Beweging
            {% elif is_state("livingroom_motion", "standby") %}
                Geen beweging
            {%- endif %}
