################################################################
## Packages / livingroom.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.livingroom: &customize
      package: 'livingroom'

    packages.livingroom_exposed: &customize_exposed
      <<: *customize

    packages.livingroom_contained: &customize_contained
      <<: *customize

    group.livingroom:
      <<: *customize_contained
      friendly_name: "Woonkamer"

    light.woonkamer_dimmer_step_size_5_6_2:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6:
      hidden: true

    light.woonkamer_dimmer_level_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0:
      <<: *customize_contained
      friendly_name: "Zithoek"

    sensor.woonkamer_dimmer_alarm_level:
      hidden: true

    sensor.woonkamer_dimmer_alarm_level_2:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type_2:
      hidden: true

    sensor.woonkamer_dimmer_exporting:
      hidden: true

    sensor.woonkamer_dimmer_heat:
      hidden: true

    sensor.woonkamer_dimmer_power_management:
      hidden: true

    sensor.woonkamer_dimmer_sourcenodeid:
      hidden: true

    sensor.woonkamer_dimmer_system:
      hidden: true

    sensor.woonkamer_dimmer_unknown_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0_3:
      hidden: true

    light.woonkamer_dimmer_level_5_0_4:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_3:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_4:
      hidden: true

    light.plafondlamp_speelkamer:
      <<: *customize_contained
      friendly_name: "Speelhoek"

    light.iris:
      <<: *customize_contained
      friendly_name: "Iris"

    light.leeslamp:
      <<: *customize_contained
      friendly_name: "Leeslamp"

################################################
## Automation
################################################

automation:

  ################################################
  ## Notification at midnight with readings from the smart meter
  ################################################
  - alias: Notify_double_click_fibaro_dimmer
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          scene_id: 14
          object_id: woonkamer_dimmer_5
    action:
      service: notify.ios_iphone_van_arno
      data_template:
        title: "Double Click detected!"
        message: "Als dit werkt betekent het dat je kunt automatiseren als reactie op een dubbel klik van de fibaro dimmer 2!"


################################################
## Group
################################################
group:
  livingroom:
    control: hidden
    entities:
      - sensor.sn1_luchtvochtigheid
      - sensor.sn1_lichtniveau
      - sensor.sn1_beweging
      - sensor.sn1_temperatuur
      - sensor.sn1_gevoelstemperatuur
      - light.woonkamer_dimmer_level_5_0
      - light.plafondlamp_speelkamer
      - light.iris
      - light.leeslamp

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "SN1 Luchtvochtigheid"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "SN1 Lichtniveau"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "SN1 Beweging"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "SN1 Temperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "SN1 Gevoelstemperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'
