################################################################
## Packages / livingroom.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.livingroom: &customize
      package: 'livingroom'

    packages.livingroom_exposed: &customize_exposed
      <<: *customize

    packages.livingroom_contained: &customize_contained
      <<: *customize

    group.livingroom:
      <<: *customize_contained
      friendly_name: "Woonkamer"

    light.woonkamer_dimmer_step_size_5_6_2:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6:
      hidden: true

    light.woonkamer_dimmer_level_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0:
      <<: *customize_contained
      hidden: true

    light.woonkamer_dimmer_level:
      <<: *customize_contained
      friendly_name: "Zithoek"

    sensor.woonkamer_dimmer_alarm_level:
      hidden: true

    sensor.woonkamer_dimmer_alarm_level_2:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type_2:
      hidden: true

    sensor.woonkamer_dimmer_exporting:
      hidden: true

    sensor.woonkamer_dimmer_heat:
      hidden: true

    sensor.woonkamer_dimmer_power_management:
      hidden: true

    sensor.woonkamer_dimmer_sourcenodeid:
      hidden: true

    sensor.woonkamer_dimmer_system:
      hidden: true

    sensor.woonkamer_dimmer_unknown_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0_3:
      hidden: true

    light.woonkamer_dimmer_level_5_0_4:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_3:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_4:
      hidden: true

    light.plafondlamp_speelkamer:
      <<: *customize_contained
      friendly_name: "Speelhoek"

    light.iris:
      <<: *customize_contained
      friendly_name: "Iris"

    light.leeslamp:
      <<: *customize_contained
      friendly_name: "Leeslamp"

    ### LIvingroom Multisensor
    sensor.livingroom_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk

    sensor.livingroom_motion:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.livingroom_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.livingroom_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.livingroom_lightlevel:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

    sensor.livingroom_heatindex:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:thermometer
      hidden: true

################################################
## Group
################################################
group:
  livingroom:
    control: hidden
    entities:
      - sensor.livingroom_motion_detector
      - sensor.livingroom_temperature
      - sensor.livingroom_humidity
      - sensor.livingroom_lightlevel
      - light.multisensor1led
      - light.woonkamer_dimmer_level
      - light.plafondlamp_speelkamer
      - light.iris
      - light.leeslamp

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_lightlevel"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "Lux"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_motion"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_temperature"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/multisensor1"
    name: "livingroom_heatindex"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'

  - platform: template
    sensors:
      livingroom_motion_detector:
        value_template: >-
            {%- if is_state("sensor.livingroom_motion", "motion detected") %}
                Beweging
            {% elif is_state("sensor.livingroom_motion", "standby") %}
                Geen beweging
            {%- endif %}

################################################
## Automation
################################################
automation:
  ################################################
  ## Light dimmed on in hallway when motion detected and in night mode
  ################################################
  - alias: hallway_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.livingroom_motion
        from: 'standby'
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamer_dimmer_level
          transition: 1
          brightness: 25

  ################################################
  ## Hhallway light off when motion no longer detected and in night mode
  ################################################
  - alias: hallway_light_off_when_no_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.livingroom_motion
        from: 'motion detected'
        to: 'standby'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamer_dimmer_level
          transition: 1
          brightness: 0

  ################################################
  ## Notification at midnight with readings from the smart meter
  ################################################
  - alias: Notify_double_click_fibaro_dimmer
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          scene_id: 14
          object_id: zwave.woonkamer_dimmer
    action:
      - service: light.toggle
        data_template:
          entity_id: light.multisensor1led
          transition: 2
      - service: tts.google_say
        data_template:
          entity_id: media_player.keuken
          message: 'Goedemorgen, het is buiten {{states('sensor.pws_temp_c')}} graden. Het voelt als {{states('sensor.pws_feelslike_c')}} en het is {{states('sensor.pws_weather')}}. Er worden temperaturen verwacht tussen de {{states('sensor.pws_temp_low_1d_c')}} en {{states('sensor.pws_temp_high_1d_c')}} graden. De weersverwachting voor vandaag is {{states('sensor.pws_weather_1d_metric')}}'
