################################################################
## Packages / livingroom.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.livingroom: &customize
      package: 'livingroom'

    packages.livingroom_exposed: &customize_exposed
      <<: *customize

    packages.livingroom_contained: &customize_contained
      <<: *customize

    group.livingroom:
      <<: *customize_contained
      friendly_name: "Woonkamer"

    light.woonkamer_dimmer_step_size_5_6_2:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6:
      hidden: true

    light.woonkamer_dimmer_level_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0:
      <<: *customize_contained
      friendly_name: "Zithoek"

    sensor.woonkamer_dimmer_alarm_level_5_1:
      hidden: true

    sensor.woonkamer_dimmer_alarm_level_5_1_2:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type_5_0:
      hidden: true

    sensor.woonkamer_dimmer_alarm_type_5_0_2:
      hidden: true

    sensor.woonkamer_dimmer_exporting_5_32:
      hidden: true

    sensor.woonkamer_dimmer_heat_5_7:
      hidden: true

    sensor.woonkamer_dimmer_power_management_5_11:
      hidden: true

    sensor.woonkamer_dimmer_sourcenodeid_5_2:
      hidden: true

    sensor.woonkamer_dimmer_system_5_12:
      hidden: true

    sensor.woonkamer_dimmer_unknown_5_0_2:
      hidden: true

    light.woonkamer_dimmer_level_5_0_3:
      hidden: true

    light.woonkamer_dimmer_level_5_0_4:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_3:
      hidden: true

    light.woonkamer_dimmer_step_size_5_6_4:
      hidden: true

    light.plafondlamp_speelkamer:
      <<: *customize_contained
      friendly_name: "Speelhoek"

    light.iris:
      <<: *customize_contained
      friendly_name: "Iris"

    light.leeslamp:
      <<: *customize_contained
      friendly_name: "Leeslamp"

################################################
## Automation
################################################

automation:

  ################################################
  ## Notification at midnight with readings from the smart meter
  ################################################
  - alias: Notify_double_click_fibaro_dimmer
    trigger:
      - platform: event
        event_type: zwave.scene_activated
        event_data:
          scene_id: 14
          object_id: woonkamer_dimmer_5
    action:
      service: notify.ios_iphone_van_arno
      data_template:
        title: "Double Click detected!"
        message: "Als dit werkt betekent het dat je kunt automatiseren als reactie op een dubbel klik van de fibaro dimmer 2!"


################################################
## Group
################################################
group:
  livingroom:
    control: hidden
    entities:
      - light.woonkamer_dimmer_level_5_0
      - light.plafondlamp_speelkamer
      - light.iris
      - light.leeslamp
