################################################
## Packages / Master Bedroom
################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.masterbedroom: &customize
      package: 'masterbedroom'

    packages.masterbedroom_exposed: &customize_exposed
      <<: *customize

    packages.masterbedroom_contained: &customize_contained
      <<: *customize

    group.masterbedroom:
      <<: *customize_contained
      friendly_name: "Ouderslaapkamer"

################################################
## Group
################################################
group:
  masterbedroom:
    control: hidden
    entities:
      - light.plafondlamp_slaapkamer
