################################################################
## Packages / House Mode
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'house_mode'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Group
    ################################################

    group.house_mode:
      <<: *customize
      friendly_name: "Huis Mode"
      icon: mdi:home-variant

    ################################################
    ## Input Boolean
    ################################################

    input_boolean.guest_mode:
      <<: *customize
      friendly_name: "Gast Mode"
      icon: mdi:account
      persistent: true

    input_boolean.vacation_mode:
      <<: *customize
      friendly_name: "Vakantie Mode"
      icon: mdi:beach
      persistent: true

    input_boolean.night_mode:
      <<: *customize
      friendly_name: "Night Mode"
      icon: mdi:weather-night
      persistent: true

    input_boolean.first_movement_of_the_day:
      <<: *customize
      friendly_name: "First movement of the day"
      icon: mdi:weather-night
      persistent: true

    input_boolean.to_bed_mode:
      <<: *customize
      friendly_name: "Naar bed Mode"
      icon: mdi:hotel
      persistent: true

    input_boolean.test_switch:
      <<: *customize
      friendly_name: "Testswitch"
      icon: mdi:test-tube
      persistent: true

    ################################################
    ## Sensor
    ################################################

    sensor.household:
      <<: *customize
      friendly_name: "Familie"

    sensor.house_mode:
      <<: *customize
      friendly_name: "Huis Mode"

################################################
## Group
################################################

group:
  house_mode:
    control: hidden
    entities:
      - sensor.house_mode
      - input_boolean.guest_mode
      - input_boolean.vacation_mode
      - input_boolean.to_bed_mode
      - input_boolean.night_mode
      - sensor.household
      - input_boolean.test_switch

################################################
## Input Boolean
################################################

input_boolean:
  guest_mode:
    initial: off

  vacation_mode:
    initial: off

  night_mode:
    initial: off

  to_bed_mode:
    initial: off

  test_switch:
    initial: off

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      household:
        entity_id: group.household
        value_template: >-
          {% if is_state('group.household', 'home') %}
            Thuis
          {% else %}
            Weg
          {% endif %}
        icon_template: >-
          {% if is_state('group.household', 'home') %}
            mdi:home
          {% else %}
            mdi:home-outline
          {% endif %}
      house_mode:
        entity_id:
          - input_boolean.guest_mode
          - input_boolean.vacation_mode
          - sensor.household
        value_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            Gasten
          {% elif is_state('sensor.household', 'home') %}
            Thuis
          {% elif is_state('input_boolean.vacation_mode', 'on') %}
            Op vakantie
          {% else %}
            Afwezig
          {% endif %}
        icon_template: >-
          {% if is_state('input_boolean.guest_mode', 'on') %}
            mdi:account
          {% elif is_state('sensor.household', 'home') %}
            mdi:home
          {% elif is_state('input_boolean.vacation_mode', 'on') %}
            mdi:beach
          {% else %}
            mdi:home-outline
          {% endif %}

binary_sensor:
  - platform: mqtt
    name: "Guest Mode Activation"
    state_topic: "ahpaleis/modes/guestmode"
    payload_on: "ON"
    payload_off: "OFF"
    #availability_topic: "home-assistant/window/availability"
    #payload_available: "online"
    #payload_not_available: "offline"
    qos: 0
    #device_class: opening
    value_template: '{{ value.x }}'
  - platform: mqtt
    name: "Test Switch"
    state_topic: "ahpaleis/modes/testswitch"
    payload_on: "ON"
    payload_off: "OFF"
    #availability_topic: "home-assistant/window/availability"
    #payload_available: "online"
    #payload_not_available: "offline"
    qos: 0
    #device_class: opening
    value_template: '{{ value.x }}'

################################################
## Automation
################################################
automation:
  - alias: "Test switch state to ON"
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.test_switch
        to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.test_switch

  - alias: "Test switch state to OFF"
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.test_switch
        to: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.test_switch

  - alias: "Going to bed sequence"
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_boolean.to_bed_mode
        to: 'on'
    action:
      - service: automation.turn_off
        entity_id: automation.hallway_light_dimup_when_motion_and_sun_above_horizon_but_dark
      - service: automation.turn_off
        entity_id: automation.hallway_light_dimup_when_motion_and_sun_below_horizon
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamerled
          color_name: darkorange
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.overloop_led
          color_name: darkorange
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.bijkeuken_led
          color_name: darkorange
          brightness: 1
          transition: 1
      - service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: "1"
      - delay: "00:00:10"
      - service: remote.turn_off
        entity_id: remote.harmony_hub
      - service: homeassistant.turn_off
        entity_id: group.mediaplayers
      - service: homeassistant.turn_off
        entity_id:
          -  group.all_switches
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamer_dimmer_level
          brightness: 1
          transition: 10
      - service: light.turn_on
        data_template:
          entity_id: light.hal_2
          color_name: red
          brightness: 1
          transition: 10
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          color_name: red
          brightness: 1
          transition: 10
      - service: light.turn_on
        data_template:
          entity_id: light.ouderslaapkamer
          color_temp: 500
          brightness: 1
          transition: 1
      - delay: '00:10:00'
      - service: homeassistant.turn_off
        entity_id:
          -  group.all_lights
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamerled
          color_name: red
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.overloop_led
          color_name: red
          brightness: 1
          transition: 1
      - service: light.turn_on
        data_template:
          entity_id: light.bijkeuken_led
          color_name: red
          brightness: 1
          transition: 1
      - service: homeassistant.turn_off
        entity_id: input_boolean.to_bed_mode
      - service: homeassistant.turn_on
        entity_id: input_boolean.night_mode

  - alias: "Night Mode On"
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_boolean.night_mode
        to: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.to_bed_mode
      - service: homeassistant.turn_off
        entity_id:
          - group.all_lights
          - remote.harmony_hub
          - group.mediaplayers
          - group.all_switches

# If first_movement_of_the_day is armed, but not triggered at sunrise, disnarm (switch input_boolean off)
# This prevents the automation to be triggered in the evening when the sun goes down in case the sun was already up before 6 am (when the input_boolean was armed)
  - alias: 'Disarm if first_movement_of_the_day is not triggered at sunrise'
    initial_state: 'on'
    trigger:
      platform: sun
      event: sunrise
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.first_movement_of_the_day'
          state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.first_movement_of_the_day
      - service: homeassistant.turn_off
        entity_id: input_boolean.night_mode
      - service: homeassistant.turn_off
        entity_id: input_boolean.to_bed_mode
      - service: automation.turn_on
        entity_id: automation.hallway_light_dimup_when_motion_and_sun_above_horizon_but_dark
      - service: automation.turn_on
        entity_id: automation.hallway_light_dimup_when_motion_and_sun_below_horizon
