################################################
## Packages / Modes
################################################
## Various input booleans to indicate different
## modes that can be active in the house
################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    packages.modes: &customize
      package: 'modes'

    packages.modes_exposed: &customize_exposed
      <<: *customize

    packages.modes_contained: &customize_contained
      <<: *customize

    input_boolean.night_mode:
      <<: *customize
      name: Nacht mode
      icon: mdi:weather-night
      persistent: true

    input_boolean.away_mode:
      <<: *customize
      name: Iedereen van Huis
      icon: mdi:security
      persistent: true

    input_boolean.to_bed_mode:
      <<: *customize
      name: Naar bed
      icon: mdi:hotel
      persistent: true

    input_boolean.guest_mode:
      <<: *customize
      name: Gast mode
      icon: mdi:account-multiple
      persistent: true
