################################################################
## Packages / Network
################################################################
## Everything related to the home (automation) network

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.network: &customize
      package: 'Netwerk'

    packages.network_exposed: &customize_exposed
      <<: *customize

    packages.network_contained: &customize_contained
      <<: *customize

    group.network:
      <<: *customize_contained
      friendly_name: "Netwerk"
      icon: mdi:access-point-network

    sensor.homeassistant:
      <<: *customize_contained
      icon: mdi:ethernet

    sensor.huehub:
      <<: *customize_contained
      icon: mdi:lightbulb-on-outline

    sensor.harmonyhub:
      <<: *customize_contained
      icon: mdi:remote

    sensor.onkyoreceiver:
      <<: *customize_contained
      icon: mdi:access-point-network

    sensor.livingroomtv:
      <<: *customize_contained
      icon: mdi:television

    sensor.chromecast_livingroom:
      <<: *customize_contained
      icon: mdi:cast

    sensor.bedroomtv:
      <<: *customize_contained
      icon: mdi:television

    sensor.chromecast_bedroom:
      <<: *customize_contained
      icon: mdi:cast

    sensor.chromecast_kitchen:
      <<: *customize_contained
      icon: mdi:cast

    sensor.retropie:
      <<: *customize_contained
      icon: mdi:gamepad-variant

    sensor.steamlink:
      <<: *customize_contained
      icon: mdi:gamepad-variant

    sensor.printer:
      <<: *customize_contained
      icon: mdi:printer

    sensor.bankhanger:
      <<: *customize_contained
      icon: mdi:volume-high

    sensor.homerouter:
      <<: *customize_contained
      icon: mdi:router-wireless

    sensor.wife_phone:
      <<: *customize_contained
      icon: mdi:cellphone-iphone

    sensor.husband_phone:
      <<: *customize_contained
      icon: mdi:cellphone-iphone
      hidden: true # replaced by iphone running the ios homeassistant app

    device_tracker.iphone_van_arno:
      <<: *customize_contained
      friendly_name: "Arno"
      icon: mdi:cellphone-iphone

    sensor.iphone_van_arno_battery_level:
      <<: *customize_contained
      friendly_name: "Arno's mobiel accu"
      icon: mdi:battery

    sensor.iphone_van_arno_battery_state:
      <<: *customize_contained
      friendly_name: "Arno's mobiel oplader"
      icon: mdi:battery

    device_tracker.iphone_van_heddy:
      <<: *customize_contained
      friendly_name: "Heddy"
      icon: mdi:cellphone-iphone

    sensor.iphone_van_heddy_battery_level:
      <<: *customize_contained
      friendly_name: "Heddy's mobiel accu"
      icon: mdi:battery

    sensor.iphone_van_heddy_battery_state:
      <<: *customize_contained
      friendly_name: "Heddy's mobiel oplader"
      icon: mdi:battery

    sensor.samsunggalaxytaba:
      <<: *customize_contained
      icon: mdi:tablet-android

    device_tracker.chromecast_slaapkamer:
      hidden: true

    device_tracker.chromecast_woonkamer:
      hidden: true

    device_tracker.chromecastkeuken:
      hidden: true

    device_tracker.harmonyhub:
      hidden: true

    device_tracker.bankhanger:
      hidden: true

    device_tracker.epsonprinter:
      hidden: true

    device_tracker.wife_phone:
      hidden: true

    device_tracker.husband_phone:
      hidden: true

    device_tracker.homeassistant:
      hidden: true

    device_tracker.huehub:
      hidden: true

    device_tracker.onkyoreceiver:
      hidden: true

    device_tracker.retropie:
      hidden: true

    device_tracker.samsunggalaxytaba:
      hidden: true

    device_tracker.slaapkamertv:
      hidden: true

    device_tracker.steamlink:
      hidden: true

    device_tracker.woonkamertv:
      hidden: true

    device_tracker.husbandlaptop:
      hidden: true

    device_tracker.ipad:
      hidden: true

    device_tracker.homeassistant_heddysiphone5s:
      hidden: true

    device_tracker.odroidjessie64:
      hidden: true

    device_tracker.home_router:
      hidden: true

################################################
## Group
################################################
group:
  network:
    control: hidden
    entities:
      - sensor.homeassistant
      - sensor.homerouter
      - sensor.huehub
      - sensor.harmonyhub
      - sensor.onkyoreceiver
      - sensor.livingroomtv
      - sensor.chromecast_livingroom
      - sensor.bedroomtv
      - sensor.chromecast_bedroom
      - sensor.chromecast_kitchen
      - sensor.retropie
      - sensor.steamlink
      - sensor.printer
      - sensor.bankhanger
      - sensor.wife_phone
      - sensor.husband_phone
      - sensor.samsunggalaxytaba


################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      chromecast_bedroom:
        friendly_name: 'Chromecast Slaapkamer'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast_slaapkamer', 'home') else 'Offline' }}"

      chromecast_livingroom:
        friendly_name: 'Chromecast Woonkamer'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecast_woonkamer', 'home') else 'Offline' }}"

      chromecast_kitchen:
        friendly_name: 'Chromecast Keuken'
        value_template: "{{ 'Online' if is_state('device_tracker.chromecastkeuken', 'home') else 'Offline' }}"

      harmonyhub:
        friendly_name: 'Harmony Hub'
        value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"

      bankhanger:
        friendly_name: 'Bankhanger Airport Express'
        value_template: "{{ 'Online' if is_state('device_tracker.bankhanger', 'home') else 'Offline' }}"

      printer:
        friendly_name: 'Epson printer'
        value_template: "{{ 'Online' if is_state('device_tracker.epsonprinter', 'home') else 'Offline' }}"

      homeassistant:
        friendly_name: 'HomeAssistant'
        value_template: "{{ 'Online' if is_state('device_tracker.odroidjessie64', 'home') else 'Offline' }}"

      huehub:
        friendly_name: 'Philips Hue hub'
        value_template: "{{ 'Online' if is_state('device_tracker.huehub', 'home') else 'Offline' }}"

      onkyoreceiver:
        friendly_name: 'Receiver woonkamer'
        value_template: "{{ 'Online' if is_state('device_tracker.onkyoreceiver', 'home') else 'Offline' }}"

      retropie:
        friendly_name: 'Retropie console'
        value_template: "{{ 'Online' if is_state('device_tracker.retropie', 'home') else 'Offline' }}"

      samsunggalaxytaba:
        friendly_name: 'Samsung tablet'
        value_template: "{{ 'Online' if is_state('device_tracker.samsunggalaxytaba', 'home') else 'Offline' }}"

      bedroomtv:
        friendly_name: 'Slaapkamer tv'
        value_template: "{{ 'Online' if is_state('device_tracker.slaapkamertv', 'home') else 'Offline' }}"

      steamlink:
        friendly_name: 'Steamlink'
        value_template: "{{ 'Online' if is_state('device_tracker.steamlink', 'home') else 'Offline' }}"

      livingroomtv:
        friendly_name: 'Woonkamer tv'
        value_template: "{{ 'Online' if is_state('device_tracker.woonkamertv', 'home') else 'Offline' }}"

      homerouter:
        friendly_name: 'Router'
        value_template: "{{ 'Online' if is_state('device_tracker.home_router', 'home') else 'Offline' }}"
