################################################################
## Packages / People
################################################################


################################################
## Customize
################################################
## Note that many/most of the sensors and device trackers here are customized in the network package
homeassistant:
  customize:
    packages.people: &customize
      package: 'People'

    packages.people_exposed: &customize_exposed
      <<: *customize

    packages.people_contained: &customize_contained
      <<: *customize

    group.family:
      <<: *customize_contained
      friendly_name: "Familie"

    group.guests:
      <<: *customize_contained
      friendly_name: "Gasten"

    group.unknown_devices:
      <<: *customize_contained
      friendly_name: "Onbekende apparaten/gasten"

    sensor.iphone_van_arno_battery_level:
      hidden: true

    sensor.iphone_van_arno_battery_state:
      hidden: true

    sensor.iphone_van_heddy_battery_level:
      hidden: true

    sensor.iphone_van_heddy_battery_state:
      hidden: true

    sensor.husband_phone_battery_sensor:
      friendly_name: !secret husband_phone_battery_sensor_name
      icon: !secret husband_phone_battery_sensor_icon

    sensor.wife_phone_battery_sensor:
      friendly_name: !secret wife_phone_battery_sensor_name
      icon: !secret wife_phone_battery_sensor_icon



################################################
## Group
################################################
group:
  family:
    control: hidden
    entities:
      - device_tracker.iphone_van_arno
      - sensor.husband_phone_battery_sensor
      - device_tracker.iphone_van_heddy
      - sensor.wife_phone_battery_sensor

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      husband_phone_battery_sensor:
        entity_id: device_tracker.iphone_van_arno
        value_template: "{{ (states.device_tracker.iphone_van_arno.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.iphone_van_arno_battery_state')|lower %}
          {% set battery_level = states('sensor.iphone_van_arno_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      wife_phone_battery_sensor:
        entity_id: device_tracker.iphone_van_heddy
        value_template: "{{ (states.device_tracker.iphone_van_heddy.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.iphone_van_heddy_battery_state')|lower %}
          {% set battery_level = states('sensor.iphone_van_heddy_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}
