################################################################
## Packages / People
################################################################


################################################
## Customize
################################################
## Note that many/most of the sensors and device trackers here are customized in the network package
homeassistant:
  customize:
    packages.people: &customize
      package: 'People'

    packages.people_exposed: &customize_exposed
      <<: *customize

    packages.people_contained: &customize_contained
      <<: *customize

    group.family:
      <<: *customize_contained
      friendly_name: "Familie"

    group.guests:
      <<: *customize_contained
      friendly_name: "Gasten"

    group.unknown_devices:
      <<: *customize_contained
      friendly_name: "Onbekende apparaten/gasten"

    sensor.iphone_van_arno_battery_level:
      hidden: true

    sensor.iphone_van_arno_battery_state:
      hidden: true

    sensor.iphone_van_heddy_battery_level:
      hidden: true

    sensor.iphone_van_heddy_battery_state:
      hidden: true

    sensor.husband_phone_battery_sensor:
      friendly_name: !secret husband_phone_battery_sensor_name
      icon: !secret husband_phone_battery_sensor_icon

    sensor.wife_phone_battery_sensor:
      friendly_name: !secret wife_phone_battery_sensor_name
      icon: !secret wife_phone_battery_sensor_icon

    device_tracker.guestdevice1:
      hidden: true

    device_tracker.guestdevice2:
      hidden: true

    device_tracker.guestdevice3:
      hidden: true

    device_tracker.guestdevice4:
      hidden: true

    device_tracker.guestdevice5:
      hidden: true

    device_tracker.guestdevice6:
      hidden: true

    device_tracker.guestdevice7:
      hidden: true

    device_tracker.guestdevice8:
      hidden: true

    device_tracker.guestdevice9:
      hidden: true

    sensor.guestdevice1_presence:
      friendly_name: !secret guestdevice1_name
      icon: !secret guestdevice1_icon

    sensor.guestdevice2_presence:
      friendly_name: !secret guestdevice2_name
      icon: !secret guestdevice2_icon

    sensor.guestdevice3_presence:
      friendly_name: !secret guestdevice3_name
      icon: !secret guestdevice3_icon

    sensor.guestdevice4_presence:
      friendly_name: !secret guestdevice4_name
      icon: !secret guestdevice4_icon

    sensor.guestdevice5_presence:
      friendly_name: !secret guestdevice5_name
      icon: !secret guestdevice5_icon

    sensor.guestdevice6_presence:
      friendly_name: !secret guestdevice6_name
      icon: !secret guestdevice6_icon

    sensor.guestdevice7_presence:
      friendly_name: !secret guestdevice7_name
      icon: !secret guestdevice7_icon

    sensor.guestdevice8_presence:
      friendly_name: !secret guestdevice8_name
      icon: !secret guestdevice8_icon

    sensor.guestdevice9_presence:
      friendly_name: !secret guestdevice9_name
      icon: !secret guestdevice9_icon

################################################
## Group
################################################
group:
  family:
    control: hidden
    entities:
      - device_tracker.iphone_van_arno
      - sensor.husband_phone_battery_sensor
      - device_tracker.iphone_van_heddy
      - sensor.wife_phone_battery_sensor

  guests:
    control: hidden
    entities:
      - sensor.guestdevice1_presence
      - sensor.guestdevice2_presence
      - sensor.guestdevice3_presence
      - sensor.guestdevice4_presence
      - sensor.guestdevice5_presence
      - sensor.guestdevice6_presence
      - sensor.guestdevice7_presence
      - sensor.guestdevice8_presence
      - sensor.guestdevice9_presence

  unknown_devices:
    control: hidden
    entities:
      - device_tracer.unknown1
      - device_tracer.unknown2
      - device_tracer.unknown3
      - device_tracer.unknown4
      - device_tracer.unknown5
      - device_tracer.unknown6
      - device_tracer.unknown7
      - device_tracer.unknown8
      - device_tracer.unknown9
      - device_tracer.unknown10

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      husband_phone_battery_sensor:
        entity_id: device_tracker.iphone_van_arno
        value_template: "{{ (states.device_tracker.iphone_van_arno.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.iphone_van_arno_battery_state')|lower %}
          {% set battery_level = states('sensor.iphone_van_arno_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      wife_phone_battery_sensor:
        entity_id: device_tracker.iphone_van_heddy
        value_template: "{{ (states.device_tracker.iphone_van_heddy.attributes|default).battery|default|int('unknown') }}"
        unit_of_measurement: '%'
        icon_template: >-
          {% set battery_state = states('sensor.iphone_van_heddy_battery_state')|lower %}
          {% set battery_level = states('sensor.iphone_van_heddy_battery_level')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% elif battery_state == 'charging' %}
            {% if battery_round < 20 %}
              {% set battery_round = 20 %}
            {% elif battery_round == 50 %}
              {% set battery_round = 60 %}
            {% elif battery_round == 70 %}
              {% set battery_round = 80 %}
            {% endif %}
            mdi:battery-charging-{{ battery_round }}
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

      guestdevice1_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice1', 'home') else 'Afwezig' }}"

      guestdevice2_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice2', 'home') else 'Afwezig' }}"

      guestdevice3_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice3', 'home') else 'Afwezig' }}"

      guestdevice4_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice4', 'home') else 'Afwezig' }}"

      guestdevice5_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice5', 'home') else 'Afwezig' }}"

      guestdevice6_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice6', 'home') else 'Afwezig' }}"

      guestdevice7_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice7', 'home') else 'Afwezig' }}"

      guestdevice8_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice8', 'home') else 'Afwezig' }}"

      guestdevice9_presence:
        value_template: "{{ 'Aanwezig' if is_state('device_tracker.guestdevice9', 'home') else 'Afwezig' }}"
