################################################################
## Packages / Scullery.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.scullery: &customize
      package: 'scullery'

    packages.scullery_exposed: &customize_exposed
      <<: *customize

    packages.scullery_contained: &customize_contained
      <<: *customize

    group.hallway:
      <<: *customize_contained
      friendly_name: "Bijkeuken"

    ### Hallway Multisensor
    sensor.scullery_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.bijkeuken_sensor_burglar_2_10:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.bijkeuken_sensor_temperature_2_1:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.bijkeuken_sensor_relative_humidity_2_5:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.bijkeuken_sensor_luminance_2_3:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

################################################
## Group
################################################
group:
  hallway:
    control: hidden
    entities:
      - sensor.scullery_motion_detector
      - sensor.bijkeuken_sensor_temperature_2_1
      - sensor.bijkeuken_sensor_relative_humidity_2_5
      - sensor.bijkeuken_sensor_luminance_2_3


################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      scullery_motion_detector:
        value_template: >-
            {%- if is_state("sensor.bijkeuken_sensor_burglar_2_10", "8") %}
                Beweging
            {% elif is_state("sensor.bijkeuken_sensor_burglar_2_10", "0") %}
                Geen beweging
            {%- endif %}
