################################################################
## Packages / Scullery.
################################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    packages.scullery: &customize
      package: 'scullery'

    packages.scullery_exposed: &customize_exposed
      <<: *customize

    packages.scullery_contained: &customize_contained
      <<: *customize

    group.scullery:
      <<: *customize_contained
      friendly_name: "Bijkeuken"

    switch.achterdeur_schakelaars_switch:
      <<: *customize_contained
      friendly_name: "Bijkeuken lamp"
      persistent: true
      icon: mdi:lightbulb

    switch.achterdeur_schakelaars_switch_2:
      <<: *customize_contained
      friendly_name: "Buitenlamp achterdeur"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_alarm_level:
      hidden: true

    sensor.achterdeur_schakelaars_alarm_type:
      hidden: true

    sensor.achterdeur_schakelaars_exporting:
      hidden: true

    sensor.achterdeur_schakelaars_exporting_2:
      hidden: true

    sensor.achterdeur_schakelaars_heat:
      hidden: true

    sensor.achterdeur_schakelaars_power_management:
      hidden: true

    sensor.achterdeur_schakelaars_sourcenodeid:
      hidden: true

    sensor.achterdeur_schakelaars_interval_4_10:
      hidden: true

    sensor.achterdeur_schakelaars_interval_4_2:
      hidden: true

    sensor.achterdeur_schakelaars_previous_reading_4_1:
      hidden: true

    sensor.achterdeur_schakelaars_previous_reading_4_9:
      hidden: true

################################################
## Group
################################################
group:
  scullery:
    control: hidden
    entities:
      - sensor.bijkeuken_temperatuur
      - sensor.bijkeuken_luchtvochtigheid
      - sensor.bijkeuken_licht
      - sensor.bijkeuken_beweging
      - light.bijkeuken_led
      - switch.achterdeur_schakelaars_switch
      - switch.achterdeur_schakelaars_switch_2

################################################
## Sensor
################################################
sensor:
  - platform: mqtt
    state_topic: "ahpaleis/scullery"
    name: "Bijkeuken luchtvochtigheid"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/scullery"
    name: "Bijkeuken licht"
    ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
    unit_of_measurement: "LUX"
    value_template: '{{ value_json.ldr }}'

  - platform: mqtt
    state_topic: "ahpaleis/scullery"
    name: "Bijkeuken beweging"
    value_template: '{{ value_json.motion }}'

  - platform: mqtt
    state_topic: "ahpaleis/scullery"
    name: "Bijkeuken temperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature | round(1) }}'

  - platform: mqtt
    state_topic: "ahpaleis/scullery"
    name: "Bijkeuken gevoelstemperatuur"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.heatIndex | round(1) }}'

################################################
## Light
################################################
light:
  - platform: mqtt_json
    name: "Bijkeuken Led"
    state_topic: "ahpaleis/scullery"
    command_topic: "ahpaleis/scullery/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

################################################
## Automation
################################################
automation:
  ################################################
  ## Light on in scullery when motion detected and not in night mode
  ################################################
  - alias: scullery_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.bijkeuken_beweging
        to: 'motion detected'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: switch.turn_on
        entity_id: switch.achterdeur_schakelaars_switch

  ################################################
  ## Scullery light off when motion no longer detected and not in night mode
  ################################################
  - alias: scullery_light_off_when_no_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.bijkeuken_beweging
        to: 'standby'
        for:
          minutes: 2
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.achterdeur_schakelaars_switch
