################################################################
## Packages / Scullery.
################################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    packages.scullery: &customize
      package: 'scullery'

    packages.scullery_exposed: &customize_exposed
      <<: *customize

    packages.scullery_contained: &customize_contained
      <<: *customize

    group.scullery:
      <<: *customize_contained
      friendly_name: "Bijkeuken"

    ### Scullery Multisensor
    sensor.scullery_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.bijkeuken_sensor_burglar:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.bijkeuken_sensor_temperature:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.bijkeuken_sensor_relative_humidity:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.bijkeuken_sensor_luminance:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

    switch.achterdeur_schakelaars_switch:
      <<: *customize_contained
      friendly_name: "Bijkeuken lamp"
      persistent: true
      icon: mdi:lightbulb

    switch.achterdeur_schakelaars_switch_2:
      <<: *customize_contained
      friendly_name: "Buitenlamp achterdeur"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_alarm_level:
      hidden: true

    sensor.achterdeur_schakelaars_alarm_type:
      hidden: true

    sensor.achterdeur_schakelaars_exporting:
      hidden: true

    sensor.achterdeur_schakelaars_exporting_2:
      hidden: true

    sensor.achterdeur_schakelaars_heat:
      hidden: true

    sensor.achterdeur_schakelaars_power_management:
      hidden: true

    sensor.achterdeur_schakelaars_sourcenodeid:
      hidden: true

    sensor.achterdeur_schakelaars_interval_4_10:
      hidden: true

    sensor.achterdeur_schakelaars_interval_4_2:
      hidden: true

    sensor.achterdeur_schakelaars_previous_reading_4_1:
      hidden: true

    sensor.achterdeur_schakelaars_previous_reading_4_9:
      hidden: true

################################################
## Group
################################################
group:
  scullery:
    control: hidden
    entities:
      - sensor.scullery_motion_detector
      - sensor.bijkeuken_sensor_temperature
      - sensor.bijkeuken_sensor_relative_humidity
      - sensor.bijkeuken_sensor_luminance
      - switch.achterdeur_schakelaars_switch
      - switch.achterdeur_schakelaars_switch_2

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      scullery_motion_detector:
        value_template: >-
            {%- if is_state("sensor.bijkeuken_sensor_burglar", "8") %}
                Beweging
            {% elif is_state("sensor.bijkeuken_sensor_burglar", "0") %}
                Geen beweging
            {%- endif %}

################################################
## Automation
################################################
automation:

  ################################################
  ## Switch on lights in scullery when motion detected
  ################################################
  - alias: scullery_light_on_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.bijkeuken_sensor_burglar
        from: '0'
        to: '8'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.achterdeur_schakelaars_switch

################################################
## Switch off lights in scullery when motion detected
################################################
## Note: This is currently triggered by the "On Time" setting
##       of the zwave sensor used. In future updates, this should be handled
##       by a timer in this configuration. Triggered by the motion sensor,
##       start a (configurable) timer, when that time has passed, switch light off.
##       If timer expires and motion is still (or again) detected by sensor, reset
##       timer and count again.
################################################
  - alias: scullery_light_off_when_motion_detected
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: state
        entity_id: sensor.bijkeuken_sensor_burglar
        from: '8'
        to: '0'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.achterdeur_schakelaars_switch
