################################################################
## Packages / Scullery.
################################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    packages.scullery: &customize
      package: 'scullery'

    packages.scullery_exposed: &customize_exposed
      <<: *customize

    packages.scullery_contained: &customize_contained
      <<: *customize

    group.scullery:
      <<: *customize_contained
      friendly_name: "Bijkeuken"

    switch.achterdeur_schakelaars_switch:
      <<: *customize_contained
      friendly_name: "Bijkeuken lamp"
      persistent: true
      icon: mdi:lightbulb

    switch.achterdeur_schakelaars_switch_2:
      <<: *customize_contained
      friendly_name: "Buitenlamp achterdeur"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_alarm_level:
      hidden: true

    sensor.achterdeur_schakelaars_alarm_type:
      hidden: true

    sensor.achterdeur_schakelaars_exporting:
      hidden: true

    sensor.achterdeur_schakelaars_exporting_2:
      hidden: true

    sensor.achterdeur_schakelaars_heat:
      hidden: true

    sensor.achterdeur_schakelaars_power_management:
      hidden: true

    sensor.achterdeur_schakelaars_sourcenodeid:
      hidden: true

    sensor.achterdeur_schakelaars_interval_4_10:
      hidden: true

    sensor.achterdeur_schakelaars_interval_4_2:
      hidden: true

    sensor.achterdeur_schakelaars_previous_reading_4_1:
      hidden: true

    sensor.achterdeur_schakelaars_previous_reading_4_9:
      hidden: true

################################################
## Group
################################################
group:
  scullery:
    control: hidden
    entities:
      - switch.achterdeur_schakelaars_switch
      - switch.achterdeur_schakelaars_switch_2

################################################
## Automation
################################################
