################################################################
## Packages / Scullery.
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.scullery: &customize
      package: 'scullery'

    packages.scullery_exposed: &customize_exposed
      <<: *customize

    packages.scullery_contained: &customize_contained
      <<: *customize

    group.scullery:
      <<: *customize_contained
      friendly_name: "Bijkeuken"

    ### Scullery Multisensor
    sensor.scullery_motion_detector:
      <<: *customize_contained
      friendly_name: "Beweging"
      icon: mdi:walk

    sensor.bijkeuken_sensor_burglar_2_10:
      <<: *customize_contained
      friendly_name: "Beweging"
      device_class: motion
      icon: mdi:walk
      hidden: true

    sensor.bijkeuken_sensor_temperature_2_1:
      <<: *customize_contained
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.bijkeuken_sensor_relative_humidity_2_5:
      <<: *customize_contained
      friendly_name: "Luchtvochtigheid"
      device_class: moisture
      icon: mdi:water-percent

    sensor.bijkeuken_sensor_luminance_2_3:
      <<: *customize_contained
      friendly_name: "Lichtniveau"
      icon: mdi:theme-light-dark

    switch.achterdeur_schakelaars_switch_4_0:
      <<: *customize_contained
      friendly_name: "Bijkeuken lamp"
      persistent: true
      icon: mdi:lightbulb

    switch.achterdeur_schakelaars_switch_4_0_2:
      <<: *customize_contained
      friendly_name: "Buitenlamp achterdeur"
      icon: mdi:lightbulb

    sensor.achterdeur_schakelaars_alarm_level_4_1:
      hidden: true

    sensor.achterdeur_schakelaars_alarm_type_4_0:
      hidden: true

    sensor.achterdeur_schakelaars_exporting_4_32:
      hidden: true

    sensor.achterdeur_schakelaars_exporting_4_32_2:
      hidden: true

    sensor.achterdeur_schakelaars_heat_4_7:
      hidden: true

    sensor.achterdeur_schakelaars_power_management_4_11:
      hidden: true

    sensor.achterdeur_schakelaars_sourcenodeid_4_2:
      hidden: true

################################################
## Group
################################################
group:
  scullery:
    control: hidden
    entities:
      - sensor.scullery_motion_detector
      - sensor.bijkeuken_sensor_temperature_2_1
      - sensor.bijkeuken_sensor_relative_humidity_2_5
      - sensor.bijkeuken_sensor_luminance_2_3
      - switch.achterdeur_schakelaars_switch_4_0
      - switch.achterdeur_schakelaars_switch_4_0_2


################################################
## Sensor
################################################

sensor:
  - platform: template
    sensors:
      scullery_motion_detector:
        value_template: >-
            {%- if is_state("sensor.bijkeuken_sensor_burglar_2_10", "8") %}
                Beweging
            {% elif is_state("sensor.bijkeuken_sensor_burglar_2_10", "0") %}
                Geen beweging
            {%- endif %}
