################################################################
## Packages / Server
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.server: &customize
      package: 'Server'

    packages.server_exposed: &customize_exposed
      <<: *customize

    packages.server_contained: &customize_contained
      <<: *customize

    sensor.cpu_use:
      <<: *customize
      friendly_name: "CPU gebruik"

    sensor.disk_use_home:
      <<: *customize
      friendly_name: "Disk Gebruik"

    sensor.ipv4_address_eth0:
      <<: *customize
      friendly_name: "IPv4 adres"

    sensor.ipv6_address_eth0:
      <<: *customize
      friendly_name: "IPv6 adres"

    sensor.last_boot:
      <<: *customize
      friendly_name: "Boot"

    sensor.pihole_ads_blocked_today:
      <<: *customize
      friendly_name: "Aantal ads geblokkeerd"

    sensor.pihole_ads_percentage_blocked_today:
      <<: *customize
      friendly_name: "Percentage ads geblokkeerd"

    sensor.pihole_dns_queries_today:
      <<: *customize
      friendly_name: "Aantal DNS queries"

    sensor.ram_free:
      <<: *customize
      friendly_name: "RAM beschikbaar"

    sensor.received_eth0:
      <<: *customize
      friendly_name: "Data in"

    sensor.sent_eth0:
      <<: *customize
      friendly_name: "Data uit"

    sensor.speedtest_ping:
      <<: *customize
      friendly_name: "Internet Ping"

    sensor.speedtest_download:
      <<: *customize
      friendly_name: "Download snelheid"

    sensor.speedtest_upload:
      <<: *customize
      friendly_name: "Upload snelheid"

    sensor.stats_mean:
      <<: *customize
      friendly_name: "Gemiddelde CPU belasting"


################################################
## Group
################################################
group:
  server:
    control: hidden
    entities:
      - sensor.cpu_use
      - sensor.disk_use_home
      - sensor.ram_free
      - sensor.ipv4_address_eth0
      - sensor.ipv6_address_eth0
      - sensor.received_eth0
      - sensor.sent_eth0
      - sensor.last_boot
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.stats_mean

################################################
## Sensor
################################################

sensor:
  - platform: speedtest
    minute:
      - 0
      - 15
      - 30
      - 45
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: cpuspeed
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot
  - platform: pi_hole
  - platform: statistics
    entity_id: sensor.cpu
  - platform: statistics
    entity_id: sensor.power_consumption
