################################################################
## Packages / Server
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.server: &customize
      package: 'Server'

    packages.server_exposed: &customize_exposed
      <<: *customize

    packages.server_contained: &customize_contained
      <<: *customize

    group.server:
      <<: *customize_contained
      friendly_name: "Server"

    group.homeassistant_install:
      <<: *customize_contained
      friendly_name: "Over HomeAssistant"

    group.internet_connection:
      <<: *customize_contained
      friendly_name: "Internetverbinding"

    sensor.cpu_used:
      <<: *customize
      friendly_name: "CPU gebruik"

    sensor.ram_available:
      <<: *customize
      friendly_name: "Geheugen beschikbar"

    sensor.disk_used_home:
      <<: *customize
      friendly_name: "Disk gebruik home-dir"

    sensor.ipv4_address_eth0:
      <<: *customize
      friendly_name: "IPv4 adres"

    sensor.ipv6_address_eth0:
      <<: *customize
      friendly_name: "IPv6 adres"

    sensor.last_boot:
      <<: *customize
      friendly_name: "Laatste reboot"

    sensor.pihole_ads_blocked_today:
      <<: *customize
      friendly_name: "Aantal ads geblokkeerd"

    sensor.pihole_dns_queries_cached:
      <<: *customize
      friendly_name: "Aantal DNS queries gecached"

    sensor.pihole_dns_queries_forwarded:
      <<: *customize
      friendly_name: "Aantal DNS queries forwarded"
    
    sensor.pihole_dns_unique_domains:
      <<: *customize
      friendly_name: "PiHole Aantal unieke domeinen"

    sensor.pihole_ads_percentage_blocked_today:
      <<: *customize
      friendly_name: "Percentage ads geblokkeerd"

    sensor.pihole_dns_queries_today:
      <<: *customize
      friendly_name: "Aantal DNS queries"
      icon: mdi:help-network

    sensor.ram_free:
      <<: *customize
      friendly_name: "RAM beschikbaar"

    sensor.received_eth0:
      <<: *customize
      friendly_name: "Data in"
      icon: mdi:download-network

    sensor.sent_eth0:
      <<: *customize
      friendly_name: "Data uit"
      icon: mdi:upload-network

    sensor.speedtest_ping:
      <<: *customize
      friendly_name: "Internet Ping"

    sensor.speedtest_download:
      <<: *customize
      friendly_name: "Download snelheid"
      icon: mdi:download-network

    sensor.speedtest_upload:
      <<: *customize
      friendly_name: "Upload snelheid"
      icon: mdi:upload-network

    sensor.stats_mean_2:
      <<: *customize
      friendly_name: "Gemiddelde CPU belasting"
      icon: mdi:memory

    sensor.cpu_temperature:
      <<: *customize
      friendly_name: "CPU temperatuur"
      icon: mdi:thermometer

    sensor.latest_ha_release:
      <<: *customize
      friendly_name: "Nieuwste HA versie beschikbaar"
      icon: mdi:floppy

    sensor.installed_ha_version:
      <<: *customize
      friendly_name: "Geinstalleerde HA versie"
      icon: mdi:floppy

    sensor.badlogin:
      <<: *customize
      friendly_name: "Mislukte inlog pogingen"
      icon: mdi:security

################################################
## Group
################################################
group:
  server:
    control: hidden
    entities:
      - sensor.cpu_used
      - sensor.ram_available
      - sensor.stats_mean_2
      - sensor.cpu_temperature
      - sensor.disk_used_home
      - sensor.ram_free
      - sensor.ipv4_address_eth0
      - sensor.ipv6_address_eth0
      - sensor.received_eth0
      - sensor.sent_eth0
  homeassistant_install:
    control: hidden
    entities:
      - sensor.homeassistant_uptime
      - sensor.last_boot
      - sensor.installed_ha_version
      - sensor.latest_ha_release
      - sensor.badlogin
      - sensor.geldigheid_certificaat
  internet_connection:
    control: hidden
    entities:
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.pihole_dns_queries_cached
      - sensor.pihole_dns_queries_forwarded
      - sensor.pihole_dns_unique_domains
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload


################################################
## Sensor
################################################

sensor:
  - platform: speedtest
    minute:
      - 0
      - 15
      - 30
      - 45
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: cpuspeed
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot
  - platform: pi_hole
  - platform: statistics
    entity_id: sensor.cpu
  - platform: statistics
    entity_id: sensor.power_consumption
  - platform: command_line
    name: "CPU temperature"
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'
  - platform: command_line
    name: "Latest HA release"
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  - platform: command_line
    name: badlogin
    command: grep -c 'Login attempt' /home/homeassistant/.homeassistant/home-assistant.log
  - platform: file
    name: "Installed HA version"
    file_path: /home/homeassistant/.homeassistant/.HA_VERSION
  - platform: cert_expiry
    name: "Geldigheid certificaat"
    host: !secret http_base_url
  - platform: command_line
    name: "HomeAssistant Uptime"
    command: echo "$(($(date +%s) - $(date --date="`systemctl show home-assistant.service -p ActiveEnterTimestamp | awk -F'=' '{print $2}'`" "+%s")))"
    scan_interval: 60
    value_template: >-
      {% set uptime = value | int %}
      {% set seconds = uptime % 60 %}
      {% set minutes = ((uptime % 3600) / 60) | int %}
      {% set hours = ((uptime % 86400) / 3600) | int %}
      {% set days = (uptime / 86400) | int %}

      {%- if days > 0 -%}
        {%- if days == 1 -%}
          1 day
        {%- else -%}
          {{ days }} days
        {%- endif -%}
      {%- endif -%}
      {%- if hours > 0 -%}
        {%- if days > 0 -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if hours == 1 -%}
          1 hour
        {%- else -%}
          {{ hours }} hours
        {%- endif -%}
      {%- endif -%}
      {%- if minutes > 0 -%}
        {%- if days > 0 or hours > 0 -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if minutes == 1 -%}
          1 minute
        {%- else -%}
          {{ minutes }} minutes
        {%- endif -%}
      {%- endif -%}
