################################################################
## Packages / Server
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.server: &customize
      package: 'Server'

    packages.server_exposed: &customize_exposed
      <<: *customize

    packages.server_contained: &customize_contained
      <<: *customize

    group.server:
      <<: *customize_contained
      friendly_name: "Server"

    sensor.cpu_use:
      <<: *customize
      friendly_name: "CPU gebruik"

    sensor.disk_use_home:
      <<: *customize
      friendly_name: "Disk Gebruik"

    sensor.ipv4_address_eth0:
      <<: *customize
      friendly_name: "IPv4 adres"

    sensor.ipv6_address_eth0:
      <<: *customize
      friendly_name: "IPv6 adres"

    sensor.last_boot:
      <<: *customize
      friendly_name: "Boot"

    sensor.pihole_ads_blocked_today:
      <<: *customize
      friendly_name: "Aantal ads geblokkeerd"

    sensor.pihole_ads_percentage_blocked_today:
      <<: *customize
      friendly_name: "Percentage ads geblokkeerd"

    sensor.pihole_dns_queries_today:
      <<: *customize
      friendly_name: "Aantal DNS queries"
      icon: mdi:help-network

    sensor.ram_free:
      <<: *customize
      friendly_name: "RAM beschikbaar"

    sensor.received_eth0:
      <<: *customize
      friendly_name: "Data in"
      icon: mdi:download-network

    sensor.sent_eth0:
      <<: *customize
      friendly_name: "Data uit"
      icon: mdi:upload-network

    sensor.speedtest_ping:
      <<: *customize
      friendly_name: "Internet Ping"

    sensor.speedtest_download:
      <<: *customize
      friendly_name: "Download snelheid"
      icon: mdi:download-network

    sensor.speedtest_upload:
      <<: *customize
      friendly_name: "Upload snelheid"
      icon: mdi:upload-network

    sensor.stats_mean:
      <<: *customize
      friendly_name: "Gemiddelde CPU belasting"
      icon: mdi:memory


################################################
## Group
################################################
group:
  server:
    control: hidden
    entities:
      - sensor.homeassistant_uptime
      - sensor.last_boot
      - sensor.cpu_use
      - sensor.stats_mean
      - sensor.disk_use_home
      - sensor.ram_free
      - sensor.ipv4_address_eth0
      - sensor.ipv6_address_eth0
      - sensor.received_eth0
      - sensor.sent_eth0
      - sensor.pihole_ads_blocked_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_queries_today
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload


################################################
## Sensor
################################################

sensor:
  - platform: speedtest
    minute:
      - 0
      - 15
      - 30
      - 45
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: cpuspeed
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot
  - platform: pi_hole
  - platform: statistics
    entity_id: sensor.cpu
  - platform: statistics
    entity_id: sensor.power_consumption
  - platform: command_line
    name: "HomeAssistant Uptime"
    command: echo "$(($(date +%s) - $(date --date="`systemctl show home-assistant.service -p ActiveEnterTimestamp | awk -F'=' '{print $2}'`" "+%s")))"
    scan_interval: 60
    value_template: >-
      {% set uptime = value | int %}
      {% set seconds = uptime % 60 %}
      {% set minutes = ((uptime % 3600) / 60) | int %}
      {% set hours = ((uptime % 86400) / 3600) | int %}
      {% set days = (uptime / 86400) | int %}

      {%- if days > 0 -%}
        {%- if days == 1 -%}
          1 day
        {%- else -%}
          {{ days }} days
        {%- endif -%}
      {%- endif -%}
      {%- if hours > 0 -%}
        {%- if days > 0 -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if hours == 1 -%}
          1 hour
        {%- else -%}
          {{ hours }} hours
        {%- endif -%}
      {%- endif -%}
      {%- if minutes > 0 -%}
        {%- if days > 0 or hours > 0 -%}
          {{ ', ' }}
        {%- endif -%}
        {%- if minutes == 1 -%}
          1 minute
        {%- else -%}
          {{ minutes }} minutes
        {%- endif -%}
      {%- endif -%}
    #  {%- if seconds > 0 -%}
    #    {%- if days > 0 or hours > 0 or minutes > 0 -%}
    #      {{ ', ' }}
    #    {%- endif -%}
    #    {%- if seconds == 1 -%}
    #      1 second
    #    {%- else -%}
    #      {{ seconds }} seconds
    #    {%- endif -%}
    #  {%- endif -%}
