################################################################
## Packages / Studio
################################################################


################################################
## Customize
################################################
homeassistant:
  customize_glob:
    "sensor.epson_ink_level_*":
      icon: mdi:cup-water
      hidden: False
  customize:
    packages.studio: &customize
      package: 'studio'

    packages.studio_exposed: &customize_exposed
      <<: *customize

    packages.studio_contained: &customize_contained
      <<: *customize

    group.studio:
      <<: *customize_contained
      friendly_name: "Studio"

    light.ailight1:
      <<: *customize_contained
      friendly_name: "Bureaulamp"

################################################
## Group
################################################
group:
  studio:
    control: hidden
    entities:
      - light.ailight1
      - device_tracker.arcadecomputer
      - device_tracker.macmini
      - device_tracker.epsonprinter
      - sensor.epson_ink_level_black
      - sensor.epson_ink_level_cyan
      - sensor.epson_ink_level_magenta
      - sensor.epson_ink_level_yellow
      - sensor.epson_ink_level_photo_black

################################################
## Sensor
################################################
sensor:
  - platform: command_line
    name: Epson Ink Level Black
    command: /usr/bin/curl -X GET http://10.0.1.9/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100; exit }'
    unit_of_measurement: '%'
    scan_interval: 60

  - platform: command_line
    name: Epson Ink Level Magenta
    command: /usr/bin/curl -X GET http://10.0.1.9/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 60

  - platform: command_line
    name: Epson Ink Level Yellow
    command: /usr/bin/curl -X GET http://10.0.1.9/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 60

  - platform: command_line
    name: Epson Ink Level Cyan
    command: /usr/bin/curl -X GET http://10.0.1.9/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
    unit_of_measurement: '%'
    scan_interval: 60

  - platform: command_line
    name: Epson Ink Waste Level
    command: /usr/bin/curl -X GET http://10.0.1.9/PRESENTATION/HTML/TOP/PRTINFO.HTML  | awk -F"'" '/Ink_Waste.PNG/ {i++}i==2 && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100; exit }'
    unit_of_measurement: '%'
    scan_interval: 60

################################################
## Light
################################################

light:
  platform: mqtt_json
  name: "ailight1"
  state_topic: 'ahpaleis/studio/desklight/status'
  command_topic: 'ahpaleis/studio/desklight/set'
  color_temp: true
  brightness: true
  rgb: true
  white_value: true
  effect: false
  optimistic: false
  retain: true

################################################
## Automation
################################################
