################################################################
## Packages / Studio
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    packages.studio: &customize
      package: 'studio'

    packages.studio_exposed: &customize_exposed
      <<: *customize

    packages.studio_contained: &customize_contained
      <<: *customize

    group.studio:
      <<: *customize_contained
      friendly_name: "Studio"

    light.ailight-1:
      <<: *customize_contained
      friendly_name: "Bureaulamp"

################################################
## Group
################################################
group:
  studio:
    control: hidden
    entities:
      - light.studio_desklight
      - device_tracker.arcadecomputer
      - device_tracker.macmini

################################################
## Sensor
################################################

################################################
## Light
################################################

light:
  platform: mqtt_json
  name: 'Studio desklight'
  state_topic: 'ahpaleis/studio/desklight'
  command_topic: 'ahpaleis/studio/desklight/set'
  color_temp: true
  brightness: true
  rgb: true
  white_value: true
  effect: false
  optimistic: false
  retain: true

################################################
## Automation
################################################
