################################################################
## Packages / Sunrise/Sunset.
################################################################
## Automations that happen around/on sunrise or sunset events
## Mostly lighting stuff
################################################################

################################################
## Customize
################################################
homeassistant:
  customize:
    packages.sunrise_sunset: &customize
      package: 'scullery'

    packages.sunrise_sunset_exposed: &customize_exposed
      <<: *customize

    packages.sunrise_sunset_contained: &customize_contained
      <<: *customize

################################################
## Group
################################################

################################################
## Sensor
################################################

################################################
## Automation
################################################
automation:
  ################################################
  ## When it gets dim, outside lights on plus hallway light
  ################################################
  - alias: gardenlights_on_when_sun_sets
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 3.5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.achterdeur_schakelaars_switch_2
      - service: homeassistant.turn_on
        entity_id: switch.tuinverlichting
      - service: light.turn_on
        data_template:
          entity_id: light.hal
          transition: 600
          brightness: 100

  ################################################
  ## when a bit darker again, switch on more lights
  ################################################
  - alias: gardenlights_on_when_sun_sets
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 1.5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
        - condition: state
          entity_id: 'group.family'
          state: 'home'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.overloop
          transition: 600
          brightness: 100
      - service: light.turn_on
        data_template:
          entity_id: light.woonkamer_dimmer_level
          transition: 900
          brightness: 200
      - service: light.turn_on
        data_template:
          entity_id: light.leeslamp
          transition: 900
          brightness: 200

  ################################################
  ## Half hour after sunrise switch off various lights
  ################################################
  - alias: lights_off_after_sunrise
    initial_state: 'on'
    hide_entity: False
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        above: 3.5
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'input_boolean.night_mode'
          state: 'off'
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.all_lights
          - switch.achterdeur_schakelaars_switch
          - switch.achterdeur_schakelaars_switch_2
          - switch.tuinverlichting
