################################################################
## Packages / Weather
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    packages.weather: &customize
      haaska_hidden: true
      homebridge_hidden: true
      package: 'Weer'

    group.weather_general:
      <<: *customize
      friendly_name: "General"

    group.weather_wunderground:
      <<: *customize
      friendly_name: "Weather Underground"

    group.weather_yr:
      <<: *customize
      friendly_name: "YR"

    automation.send_weather_forecast_in_the_morning:
      <<: *customize
      friendly_name: "Weersverwachting vandaag"
      icon: mdi:comment-alert-outline

    automation.send_weather_forecast_in_the_evening:
      <<: *customize
      friendly_name: "Weersverwachting vannacht"
      icon: mdi:comment-alert-outline

    sensor.pws_feelslike_c:
      <<: *customize
      friendly_name: "Gevoelstemperatuur"
      icon: mdi:thermometer

    sensor.pws_precip_today_mm:
      <<: *customize
      friendly_name: "Neerslag"
      icon: mdi:weather-rainy

    sensor.pws_relative_humidity:
      <<: *customize
      friendly_name: "Luchtvochtigheid"
      icon: mdi:water-percent

    sensor.pws_temp_c:
      <<: *customize
      friendly_name: "Temperatuur"
      icon: mdi:thermometer

    sensor.pws_weather:
      <<: *customize
      friendly_name: "Huidige condities"

    sensor.pws_precip_1d:
      <<: *customize
      friendly_name: "Neerslagkans vandaag"

    sensor.pws_precip_1d_mm:
      <<: *customize
      friendly_name: "Neerslag voorspelling"

    sensor.pws_precip_today_metric:
      <<: *customize
      friendly_name: "Neerslag vandaag"

    sensor.pws_temp_high_1d_c:
      <<: *customize
      friendly_name: "Hoogste temperatuur vandaag"

    sensor.pws_temp_low_1d_c:
      <<: *customize
      friendly_name: "Laagste temperatuur vandaag"

    #sensor.pws_temp_high_record_c:
    #  <<: *customize
    #  friendly_name: "Hoogst gemeten temperatuur op deze dag"

    #sensor.pws_temp_low_record_c:
    #  <<: *customize
    #  friendly_name: "Laagst gemeten temperatuur op deze dag"

    sensor.pws_precip_1hr_metric:
      <<: *customize
      friendly_name: "Verwachtte neerslag het komende uur"

    sensor.wind_1d_kph:
      <<: *customize
      friendly_name: "Windverwachting"

################################################
## Automation
################################################

automation:

  ################################################
  ## Notification at midnight with readings from the smart meter
  ################################################
  - alias: send_weather_forecast_in_the_morning
    initial_state: 'on'
    trigger:
      - platform: time
        after: '06:00:00'
    action:
      service: notify.ios_iphone_van_arno
      data_template:
        title: "Weersverwachting"
        message: "Vandaag: {{ states.sensor.pws_weather_1d_metric.state }}"

  - alias: send_weather_forecast_in_the_evening
    initial_state: 'on'
    trigger:
      - platform: time
        after: '18:00:00'
    action:
      service: notify.ios_iphone_van_arno
      data_template:
        title: "Weersverwachting"
        message: "Avond & nacht: {{ states.sensor.pws_weather_1n_metric.state }}"
################################################
## Group
################################################

group:
  weather_combined:
    name: Weer
    control: hidden
    entities:
      - sensor.pws_temp_c
      - sensor.pws_feelslike_c
      - sensor.pws_relative_humidity
      - sensor.wind_1d_kph
      - sensor.pws_precip_1hr_metric
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_mm
      - sensor.pws_precip_today_metric
      - sensor.pws_weather
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_low_1d_c
      - sun.sun
      - sensor.pws_temp_high_record_c
      #- sensor.pws_temp_low_record_c


  dialy_forecast:
    name: Vooruitzichten
    entities:
      - sensor.pws_weather_1d_metric
      - sensor.pws_weather_1n_metric
      - sensor.pws_weather_2d_metric
      - sensor.pws_weather_2n_metric
      - sensor.pws_weather_3d_metric
      - sensor.pws_weather_3n_metric
      - sensor.pws_weather_4d_metric
      - sensor.pws_weather_4n_metric

################################################
## Sensor
################################################

sensor:
#  - platform: darksky
#    api_key: !secret darksky_api_key
#    monitored_conditions:
#      - cloud_cover
#      - humidity
#      - precip_probability
#      - temperature

  - platform: wunderground
    api_key: !secret wunderground_api
    lang: NL
    monitored_conditions:
      - feelslike_c
      - heat_index_c
      - precip_today_metric
      - precip_1hr_metric
      - precip_1d_mm
      - precip_1d
      - relative_humidity
      - temp_c
      - temp_high_record_c
      - temp_low_record_c
      - temp_high_1d_c
      - temp_low_1d_c
      - wind_1d_kph
      - weather
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - weather_4d_metric
      - weather_4n_metric
